#!/usr/bin/env python3
"""Generate L5 Civilization Memory entries."""
import yaml
import os

OUTPUT_DIR = "data/entries/L5_civilization_memory"

ENTRIES = [
    # MATHEMATICS
    {
        "id": "l5-math-trigonometry",
        "title": "Trigonometry for Angle and Distance Calculation",
        "subtopic": "math",
        "tags": ["math", "trigonometry", "surveying"],
        "summary": "Sine, cosine, and tangent ratios for calculating angles, heights, and distances in construction and surveying.",
        "steps": [
            "Learn the three primary trig ratios: sin = opposite/hypotenuse, cos = adjacent/hypotenuse, tan = opposite/adjacent.",
            "Memorize key angle values: 30°, 45°, 60°, 90° and their ratios.",
            "Apply tangent to measure heights of structures or trees using shadow length.",
            "Use sine rule and cosine rule for non-right triangles in land surveying.",
            "Practice triangulation: measure one baseline and two angles to find unknown distances.",
        ],
        "warnings": ["Small angle measurement errors multiply over distance.", "Always verify with a second method when possible."],
        "related_entries": ["l5-math-foundations", "l5-math-geometry-construction", "l5-nav-dead-reckoning"],
        "sources": ["openstax-precalculus", "openstax-calculus-volume-1"],
    },
    {
        "id": "l5-math-statistics-basics",
        "title": "Basic Statistics for Decision-Making",
        "subtopic": "math",
        "tags": ["math", "statistics", "probability", "decision-making"],
        "summary": "Mean, median, mode, and basic probability concepts for resource planning and risk assessment.",
        "steps": [
            "Calculate mean (average) for resource consumption estimates.",
            "Use median to find the middle value when outliers skew data.",
            "Track mode to identify the most common outcome in repeated observations.",
            "Estimate simple probability as favorable outcomes / total outcomes.",
            "Apply expected value (probability × outcome) to compare risky decisions.",
        ],
        "warnings": ["Small sample sizes produce unreliable statistics.", "Correlation does not imply causation—verify with controlled observation."],
        "related_entries": ["l5-math-foundations", "l5-governance-resource-allocation", "l5-edu-scientific-method"],
        "sources": ["openstax-precalculus"],
    },
    {
        "id": "l5-math-measurement-systems",
        "title": "Measurement Systems and Unit Conversion",
        "subtopic": "math",
        "tags": ["math", "measurement", "units", "estimation"],
        "summary": "Metric and imperial unit systems, conversion factors, and body-based estimation techniques.",
        "steps": [
            "Learn key metric units: meter, kilogram, liter, and their prefixes (milli, centi, kilo).",
            "Learn key imperial units: foot, pound, gallon and conversion to metric.",
            "Memorize critical conversions: 1 inch ≈ 2.54 cm, 1 kg ≈ 2.2 lb, 1 mile ≈ 1.6 km.",
            "Use body-based estimation: arm span ≈ height, pace length, hand span.",
            "Always record units with every measurement to prevent errors.",
        ],
        "warnings": ["Unit mismatch is a leading cause of engineering failures.", "Estimation is for planning only—measure precisely before building."],
        "related_entries": ["l5-math-foundations", "l5-math-trigonometry", "l5-nav-dead-reckoning"],
        "sources": ["openstax-precalculus"],
    },
    {
        "id": "l5-math-geometry-construction",
        "title": "Practical Geometry with Compass and Straightedge",
        "subtopic": "math",
        "tags": ["math", "geometry", "construction", "drafting"],
        "summary": "Compass-and-straightedge methods for laying out perpendicular lines, bisecting angles, and constructing regular shapes.",
        "steps": [
            "Construct a perpendicular bisector: arc from each endpoint, connect intersections.",
            "Bisect any angle with equal arcs from the vertex, then arc from each intersection.",
            "Construct a right angle using a 3-4-5 triangle with rope or stakes.",
            "Lay out a square foundation by constructing perpendiculars at corners.",
            "Create regular polygons (hexagon, octagon) inscribed in circles for structural layouts.",
        ],
        "warnings": ["Use taut string or rigid straightedge—sagging introduces error.", "Mark points clearly; lost reference marks require starting over."],
        "related_entries": ["l5-math-foundations", "l5-math-trigonometry", "l5-structural-foundation-types"],
        "sources": ["openstax-precalculus"],
    },
    # MECHANICAL ENGINEERING
    {
        "id": "l5-mech-thermodynamics-basics",
        "title": "Thermodynamics Basics: Heat Engines and Energy Conversion",
        "subtopic": "mechanical_engineering",
        "tags": ["mechanical_engineering", "thermodynamics", "heat", "energy"],
        "summary": "Fundamental principles of heat transfer and energy conversion for building simple engines and heating systems.",
        "steps": [
            "Understand the three modes of heat transfer: conduction, convection, radiation.",
            "Learn the concept of work from expanding gases (piston principle).",
            "Grasp thermal efficiency: no engine converts all heat to work (second law).",
            "Apply insulation principles to reduce unwanted heat loss.",
            "Design simple steam or hot-air engines using pressure differentials.",
        ],
        "warnings": ["Pressurized vessels can explode—always include pressure relief.", "Burns from steam are more severe than from dry heat at the same temperature."],
        "related_entries": ["l5-mechanical-engineering-basics", "l5-mech-fluid-mechanics-basics", "l5-metallurgy-iron-smelting"],
        "sources": ["mit-ocw-mechanical-engineering", "openstax-college-physics"],
    },
    {
        "id": "l5-mech-fluid-mechanics-basics",
        "title": "Fluid Mechanics: Pipe Flow, Hydraulics, and Pumps",
        "subtopic": "mechanical_engineering",
        "tags": ["mechanical_engineering", "hydraulics", "pumps", "water"],
        "summary": "Principles of fluid flow for designing water systems, hydraulic presses, and simple pumps.",
        "steps": [
            "Understand pressure = force / area and how it transmits through fluids (Pascal's principle).",
            "Calculate flow rate: cross-sectional area × velocity.",
            "Apply gravity-fed systems: 1 meter of head ≈ 9.8 kPa (1.42 psi) pressure.",
            "Build simple pumps: piston pump, rope pump, or ram pump for water lifting.",
            "Minimize friction losses with smooth, large-diameter pipes and few bends.",
        ],
        "warnings": ["Water hammer from sudden valve closure can burst pipes.", "Ensure intake screens to prevent debris from jamming pumps."],
        "related_entries": ["l5-mechanical-engineering-basics", "l5-mech-thermodynamics-basics", "l5-health-water-infrastructure"],
        "sources": ["mit-ocw-mechanical-engineering", "openstax-college-physics"],
    },
    {
        "id": "l5-mech-gear-and-linkage",
        "title": "Gears and Linkages: Power Transmission Mechanisms",
        "subtopic": "mechanical_engineering",
        "tags": ["mechanical_engineering", "gears", "linkage", "power_transmission"],
        "summary": "How to transmit and transform rotary and linear motion using gears, pulleys, levers, and linkages.",
        "steps": [
            "Apply lever classes: first (fulcrum between), second (load between), third (effort between).",
            "Use gear ratios to trade speed for torque: large driving small = faster, less torque.",
            "Build simple pulley systems: each additional pulley halves the required force.",
            "Create linkages (four-bar, crank-slider) to convert rotary to linear motion.",
            "Fabricate wooden or cast-metal gears for low-speed, high-torque applications.",
        ],
        "warnings": ["Gear teeth must mesh properly or they strip under load.", "Keep fingers and loose clothing away from moving mechanisms."],
        "related_entries": ["l5-mechanical-engineering-basics", "l5-mech-bearings-and-lubrication", "l5-mech-materials-strength"],
        "sources": ["mit-ocw-mechanical-engineering"],
    },
    {
        "id": "l5-mech-materials-strength",
        "title": "Materials Strength: Stress, Strain, and Safety Factors",
        "subtopic": "mechanical_engineering",
        "tags": ["mechanical_engineering", "materials", "stress", "safety"],
        "summary": "Understanding how materials respond to loads, and how to apply safety factors to prevent failure.",
        "steps": [
            "Define stress (force/area) and strain (deformation/original length).",
            "Identify yield strength (permanent deformation begins) vs. ultimate strength (failure).",
            "Apply safety factors: design load = ultimate strength / safety factor (typically 2-4 for critical structures).",
            "Recognize failure modes: tension, compression, shear, buckling, fatigue.",
            "Test materials empirically when data is unavailable—load incrementally and observe.",
        ],
        "warnings": ["Fatigue failure occurs below yield strength after many load cycles.", "Notches and holes concentrate stress—round all corners."],
        "related_entries": ["l5-mechanical-engineering-basics", "l5-structural-load-paths", "l5-metallurgy-tempering-hardening"],
        "sources": ["mit-ocw-mechanical-engineering", "openstax-engineering-statics"],
    },
    {
        "id": "l5-mech-bearings-and-lubrication",
        "title": "Bearings and Lubrication: Friction Reduction",
        "subtopic": "mechanical_engineering",
        "tags": ["mechanical_engineering", "bearings", "lubrication", "friction"],
        "summary": "How to reduce friction in rotating and sliding mechanisms using bearings and lubricants.",
        "steps": [
            "Understand sliding vs. rolling friction—rolling contact drastically reduces resistance.",
            "Fabricate plain bearings from hardwood, bone, or cast bronze for shafts.",
            "Use ball or roller bearings salvaged from vehicles for high-speed applications.",
            "Apply lubricants: animal fat, plant oils, or petroleum products between sliding surfaces.",
            "Maintain bearings: keep clean, re-lubricate regularly, replace when worn.",
        ],
        "warnings": ["Dry bearings overheat and seize, potentially causing fires.", "Contaminated lubricant accelerates wear—filter or replace regularly."],
        "related_entries": ["l5-mechanical-engineering-basics", "l5-mech-gear-and-linkage", "l5-metallurgy-copper-working"],
        "sources": ["mit-ocw-mechanical-engineering"],
    },
    # METALLURGY
    {
        "id": "l5-metallurgy-iron-smelting",
        "title": "Iron Smelting: Bloomery Iron from Ore",
        "subtopic": "metallurgy",
        "tags": ["metallurgy", "iron", "smelting", "bloomery"],
        "summary": "How to produce usable iron from ore using a bloomery furnace with charcoal fuel.",
        "steps": [
            "Identify iron ore: look for heavy, reddish-brown rocks (hematite, magnetite, bog iron).",
            "Build a bloomery furnace from clay/stone, ~1m tall with tuyere (air inlet) near base.",
            "Produce charcoal by slow-burning hardwood in a covered pit.",
            "Charge furnace with alternating layers of charcoal and crushed ore.",
            "Maintain forced air (bellows) for 6-10 hours to reach ~1200°C; extract bloom and hammer out slag.",
        ],
        "warnings": ["Extreme heat and carbon monoxide—work outdoors with ventilation.", "Molten slag causes severe burns; wear protection and keep water away from furnace."],
        "related_entries": ["l5-metallurgy-basics", "l5-metallurgy-tempering-hardening", "l5-metallurgy-welding-basics"],
        "sources": ["usgs-mineral-education", "openstax-chemistry-2e"],
    },
    {
        "id": "l5-metallurgy-copper-working",
        "title": "Copper Working: Native Copper and Simple Smelting",
        "subtopic": "metallurgy",
        "tags": ["metallurgy", "copper", "smelting", "bronze"],
        "summary": "Working native copper and smelting copper ore for tools, vessels, and eventually bronze alloys.",
        "steps": [
            "Find native copper nuggets in streambeds or green-stained rocks (malachite, azurite) for ore.",
            "Cold-work native copper by hammering; anneal (heat to red and quench) to restore malleability.",
            "Smelt copper ore in a charcoal furnace with bellows at ~1100°C.",
            "Cast copper into molds for axes, vessels, and fittings.",
            "Alloy with tin (5-12%) to create bronze—harder and better for tools.",
        ],
        "warnings": ["Copper smelting produces toxic fumes—smelt only outdoors.", "Molten copper splashes violently if it contacts moisture."],
        "related_entries": ["l5-metallurgy-basics", "l5-metallurgy-casting-basics", "l5-mech-bearings-and-lubrication"],
        "sources": ["usgs-mineral-education", "openstax-chemistry-2e"],
    },
    {
        "id": "l5-metallurgy-casting-basics",
        "title": "Metal Casting: Sand Casting and Mold Making",
        "subtopic": "metallurgy",
        "tags": ["metallurgy", "casting", "molds", "foundry"],
        "summary": "Sand casting technique for reproducing metal parts using reusable patterns and sand molds.",
        "steps": [
            "Create a pattern of the desired part from wood or existing object.",
            "Pack greensand (sand + clay + water) around the pattern in a two-part flask (cope and drag).",
            "Remove the pattern, cut gates and risers for metal flow and air escape.",
            "Melt metal in a crucible furnace and pour into the mold cavity.",
            "Allow to cool, break out casting, and finish by filing and grinding.",
        ],
        "warnings": ["Molten metal is extremely dangerous—wear full protective gear.", "Moisture in the mold causes steam explosions—dry sand thoroughly."],
        "related_entries": ["l5-metallurgy-basics", "l5-metallurgy-copper-working", "l5-metallurgy-iron-smelting"],
        "sources": ["usgs-mineral-education", "mit-ocw-mechanical-engineering"],
    },
    {
        "id": "l5-metallurgy-tempering-hardening",
        "title": "Heat Treatment: Tempering and Hardening for Tools",
        "subtopic": "metallurgy",
        "tags": ["metallurgy", "heat_treatment", "tempering", "hardening"],
        "summary": "How to harden and temper steel tools for optimal edge retention and toughness.",
        "steps": [
            "Heat steel to critical temperature (cherry red, ~800°C) uniformly.",
            "Quench in water or oil for maximum hardness (martinsite formation).",
            "Clean the surface bright to observe temper colors.",
            "Reheat slowly and watch oxide colors: straw (220°C) for cutting edges, blue (300°C) for springs.",
            "Quench again when desired color reaches the working edge.",
        ],
        "warnings": ["Over-hardened steel is brittle and shatters—always temper after hardening.", "Quenching hot metal in water produces steam—keep face clear."],
        "related_entries": ["l5-metallurgy-basics", "l5-metallurgy-iron-smelting", "l5-mech-materials-strength"],
        "sources": ["usgs-mineral-education", "openstax-chemistry-2e"],
    },
    {
        "id": "l5-metallurgy-welding-basics",
        "title": "Forge Welding Fundamentals",
        "subtopic": "metallurgy",
        "tags": ["metallurgy", "welding", "forge", "joining"],
        "summary": "Joining iron and steel pieces by heating to welding temperature and hammering together.",
        "steps": [
            "Prepare joint surfaces: scarf (overlap) or butt joint, clean of scale and dirt.",
            "Apply flux (borax or fine sand) to prevent oxidation at the joint.",
            "Heat both pieces to bright yellow/white heat (~1300°C for mild steel).",
            "Quickly bring pieces together and strike with firm, rapid hammer blows.",
            "Reheat and re-strike as needed; inspect by bending—a good weld won't separate.",
        ],
        "warnings": ["Welding temperature steel throws sparks—clear flammable materials.", "Flux spatters on contact—wear eye protection and leather apron."],
        "related_entries": ["l5-metallurgy-basics", "l5-metallurgy-iron-smelting", "l5-metallurgy-tempering-hardening"],
        "sources": ["usgs-mineral-education", "mit-ocw-mechanical-engineering"],
    },
    # STRUCTURAL ENGINEERING
    {
        "id": "l5-structural-foundation-types",
        "title": "Foundation Types: Footings, Piers, and Slabs",
        "subtopic": "structural_engineering",
        "tags": ["structural_engineering", "foundations", "construction"],
        "summary": "Choosing and building appropriate foundations based on soil conditions and structure type.",
        "steps": [
            "Assess soil: dig test pits to check bearing capacity—clay, sand, rock, or fill.",
            "Use spread footings for walls: widen the base to distribute load over soft soil.",
            "Use pier/post foundations on slopes or in wet areas to elevate the structure.",
            "Build slab-on-grade for simple structures on stable, level ground.",
            "Ensure foundations extend below frost line to prevent heaving.",
        ],
        "warnings": ["Poor foundations cause total structural failure—never skip soil assessment.", "Wet or expansive clay soils require special drainage and wider footings."],
        "related_entries": ["l5-structural-load-paths", "l5-structural-masonry-basics", "l5-math-geometry-construction"],
        "sources": ["openstax-engineering-statics", "mit-ocw-mechanical-engineering"],
    },
    {
        "id": "l5-structural-truss-design",
        "title": "Truss Design: Triangulated Load Distribution",
        "subtopic": "structural_engineering",
        "tags": ["structural_engineering", "truss", "roof", "bridge"],
        "summary": "Using triangulated frameworks to span distances efficiently with minimal material.",
        "steps": [
            "Understand that triangles are inherently rigid—the basis of all trusses.",
            "Design common truss types: king post (simplest), queen post, Howe, Pratt.",
            "Calculate member forces using method of joints or method of sections.",
            "Size members: tension members can be thinner; compression members must resist buckling.",
            "Connect joints with gusset plates, pegs, bolts, or lashed connections.",
        ],
        "warnings": ["A single failed member can cause progressive truss collapse.", "Compression members must be braced against lateral buckling."],
        "related_entries": ["l5-structural-load-paths", "l5-structural-bridge-basics", "l5-structural-timber-framing"],
        "sources": ["openstax-engineering-statics", "mit-ocw-mechanical-engineering"],
    },
    {
        "id": "l5-structural-masonry-basics",
        "title": "Masonry Basics: Brick and Stone Wall Construction",
        "subtopic": "structural_engineering",
        "tags": ["structural_engineering", "masonry", "brick", "stone"],
        "summary": "Building durable walls from brick or stone with proper bonding patterns and mortar.",
        "steps": [
            "Select materials: fired brick, stone, or concrete block; lime or clay mortar.",
            "Lay courses with staggered joints (running bond) to distribute loads.",
            "Use a level and plumb line to keep walls vertical and courses horizontal.",
            "Build corners first, then fill between using string lines for alignment.",
            "Include lintels over openings (stone, timber, or steel) to carry wall loads.",
        ],
        "warnings": ["Unreinforced masonry is weak in earthquakes—add buttresses or reinforcement.", "Mortar must cure slowly—keep damp for several days."],
        "related_entries": ["l5-structural-load-paths", "l5-structural-foundation-types", "l5-structural-earthen-construction"],
        "sources": ["openstax-engineering-statics"],
    },
    {
        "id": "l5-structural-timber-framing",
        "title": "Timber Framing: Post-and-Beam Construction",
        "subtopic": "structural_engineering",
        "tags": ["structural_engineering", "timber", "framing", "carpentry"],
        "summary": "Post-and-beam construction techniques using large timbers joined with traditional joinery.",
        "steps": [
            "Select straight, seasoned hardwood timbers; size posts and beams to span requirements.",
            "Cut mortise-and-tenon joints for beam-to-post connections.",
            "Secure joints with wooden pegs (treenails) driven through offset holes for draw-boring.",
            "Raise bents (assembled frames) and connect with plates, girts, and braces.",
            "Add diagonal bracing to resist lateral forces (wind, earthquake).",
        ],
        "warnings": ["Green timber shrinks and loosens joints—season wood before use.", "Raising heavy bents requires coordinated crew and safe rigging."],
        "related_entries": ["l5-structural-load-paths", "l5-structural-truss-design", "l5-structural-foundation-types"],
        "sources": ["usfs-wood-handbook-2021", "openstax-engineering-statics"],
    },
    {
        "id": "l5-structural-bridge-basics",
        "title": "Bridge Basics: Beam, Arch, and Suspension Principles",
        "subtopic": "structural_engineering",
        "tags": ["structural_engineering", "bridge", "arch", "suspension"],
        "summary": "Fundamental bridge types, their load-carrying principles, and when to use each.",
        "steps": [
            "Beam bridges: simplest type; span limited by material strength and depth.",
            "Arch bridges: convert vertical loads to compression along the curve into abutments.",
            "Suspension bridges: cables in tension carry the deck via hangers; requires strong anchorages.",
            "Select bridge type based on span, materials available, and load requirements.",
            "Always include safety railings, approach grading, and drainage.",
        ],
        "warnings": ["Dynamic loads (marching, wind) can cause resonance—break step on bridges.", "Abutments must be anchored in solid ground or rock."],
        "related_entries": ["l5-structural-load-paths", "l5-structural-truss-design", "l5-structural-foundation-types"],
        "sources": ["openstax-engineering-statics", "mit-ocw-mechanical-engineering"],
    },
    {
        "id": "l5-structural-earthen-construction",
        "title": "Earthen Construction: Adobe, Rammed Earth, and Cob",
        "subtopic": "structural_engineering",
        "tags": ["structural_engineering", "earthen", "adobe", "rammed_earth", "cob"],
        "summary": "Building durable structures from earth-based materials available almost anywhere.",
        "steps": [
            "Test soil: ideal mix is ~70% sand, 30% clay; adjust with additives.",
            "Adobe: form wet earth-straw mix into bricks, dry in sun for 2-4 weeks.",
            "Rammed earth: compact damp soil in formwork layers of 10-15 cm.",
            "Cob: hand-mix earth, sand, straw, and water; build in lifts without forms.",
            "Protect all earthen walls with roof overhangs and waterproof foundation courses.",
        ],
        "warnings": ["Earthen walls dissolve in prolonged rain without protection.", "Thick walls are needed for structural strength—minimum 30 cm."],
        "related_entries": ["l5-structural-load-paths", "l5-structural-masonry-basics", "l5-structural-foundation-types"],
        "sources": ["openstax-engineering-statics"],
    },
    # GOVERNANCE
    {
        "id": "l5-governance-conflict-resolution",
        "title": "Conflict Resolution: Mediation and De-escalation",
        "subtopic": "governance",
        "tags": ["governance", "conflict", "mediation", "leadership"],
        "summary": "Techniques for resolving disputes peacefully through structured mediation and de-escalation.",
        "steps": [
            "Separate parties and allow cooling-off period before mediation.",
            "Select a neutral mediator acceptable to both parties.",
            "Let each side state their position without interruption.",
            "Identify underlying interests (needs) vs. stated positions (demands).",
            "Seek mutually acceptable solutions; document agreements and follow up.",
        ],
        "warnings": ["Unresolved conflicts escalate—address disputes early.", "Mediator must remain genuinely neutral or lose credibility."],
        "related_entries": ["l5-governance-principles", "l5-governance-law-basics", "l5-governance-resource-allocation"],
        "sources": ["openstax-intro-business-governance"],
    },
    {
        "id": "l5-governance-resource-allocation",
        "title": "Resource Allocation: Fair Distribution Systems",
        "subtopic": "governance",
        "tags": ["governance", "resources", "distribution", "rationing"],
        "summary": "Methods for fair and transparent allocation of scarce resources in a community.",
        "steps": [
            "Inventory all available resources and estimate consumption rates.",
            "Establish priority categories: survival needs first, then comfort, then luxury.",
            "Use per-capita rationing for essentials (food, water, medicine).",
            "Create transparent tracking systems visible to the community.",
            "Review and adjust allocations regularly based on changing conditions.",
        ],
        "warnings": ["Perceived unfairness causes social breakdown faster than actual scarcity.", "Secret stockpiles destroy trust—maintain transparency."],
        "related_entries": ["l5-governance-principles", "l5-governance-conflict-resolution", "l5-governance-record-keeping"],
        "sources": ["openstax-intro-business-governance"],
    },
    {
        "id": "l5-governance-record-keeping",
        "title": "Record Keeping: Documentation and Archives",
        "subtopic": "governance",
        "tags": ["governance", "records", "archives", "documentation"],
        "summary": "Systems for maintaining community records, inventories, and institutional knowledge.",
        "steps": [
            "Designate a record keeper and establish standard formats.",
            "Record vital statistics: births, deaths, marriages, population counts.",
            "Maintain resource inventories with regular audits.",
            "Document decisions, agreements, and the reasoning behind them.",
            "Store records in multiple locations to protect against loss.",
        ],
        "warnings": ["Records on paper require protection from water, fire, and insects.", "Undocumented decisions lead to disputes—write it down."],
        "related_entries": ["l5-governance-principles", "l5-governance-resource-allocation", "l5-edu-library-preservation"],
        "sources": ["openstax-intro-business-governance"],
    },
    {
        "id": "l5-governance-law-basics",
        "title": "Law Basics: Establishing Rules and Enforcement",
        "subtopic": "governance",
        "tags": ["governance", "law", "rules", "justice"],
        "summary": "Creating a basic legal framework with clear rules, due process, and proportional enforcement.",
        "steps": [
            "Establish core rules by community consensus focusing on safety and cooperation.",
            "Write rules in plain language; post publicly for all to see.",
            "Create due process: accused must be heard before judgment.",
            "Apply proportional consequences—punishment fits the offense.",
            "Establish an appeals process to prevent abuse of authority.",
        ],
        "warnings": ["Arbitrary enforcement destroys rule of law—apply rules consistently.", "Overly harsh penalties breed resentment and rebellion."],
        "related_entries": ["l5-governance-principles", "l5-governance-conflict-resolution", "l5-governance-record-keeping"],
        "sources": ["openstax-intro-business-governance"],
    },
    {
        "id": "l5-governance-trade-barter",
        "title": "Trade and Barter: Exchange Systems Without Currency",
        "subtopic": "governance",
        "tags": ["governance", "trade", "barter", "economics"],
        "summary": "Establishing fair exchange systems for goods and services when currency is unavailable.",
        "steps": [
            "Identify community surpluses and deficits to find trade opportunities.",
            "Establish common value benchmarks (e.g., labor-hours, grain weight) for comparison.",
            "Use direct barter for simple two-party exchanges.",
            "Create credit/debt tracking for deferred exchanges (IOUs with witnesses).",
            "Designate market days and neutral trading locations for inter-community exchange.",
        ],
        "warnings": ["Barter is inefficient for complex economies—develop commodity money when stable.", "Disputes over value require pre-agreed arbitration."],
        "related_entries": ["l5-governance-principles", "l5-governance-resource-allocation", "l5-governance-record-keeping"],
        "sources": ["openstax-intro-business-governance"],
    },
    # COMMUNICATION
    {
        "id": "l5-comm-signal-methods",
        "title": "Signal Methods: Visual and Audio Signaling",
        "subtopic": "communication",
        "tags": ["communication", "signals", "flags", "mirrors"],
        "summary": "Using flags, mirrors, smoke, horns, and drums for long-distance communication without electronics.",
        "steps": [
            "Establish a shared signal code (e.g., flag positions, drum patterns).",
            "Use mirror signals (heliograph) for daytime line-of-sight communication up to 50+ km.",
            "Use smoke signals with wet fuel for visible plumes; pre-agreed patterns.",
            "Sound signals: horns, bells, drums carry 1-5 km depending on terrain.",
            "Set up relay stations on hilltops for extended range communication chains.",
        ],
        "warnings": ["Signals are visible to everyone—assume hostile observers.", "Weather (fog, wind) degrades both visual and audio signals."],
        "related_entries": ["l5-communication-systems-basics", "l5-comm-messenger-networks", "l5-comm-encryption-basics"],
        "sources": ["army-land-navigation-fm-3-25-26", "bsa-handbook"],
    },
    {
        "id": "l5-comm-writing-systems",
        "title": "Writing Systems: Preserving Written Language",
        "subtopic": "communication",
        "tags": ["communication", "writing", "literacy", "preservation"],
        "summary": "Maintaining and teaching writing for record-keeping and knowledge preservation.",
        "steps": [
            "Prioritize literacy education for all community members.",
            "Produce ink from charcoal/soot mixed with water and a binder (gum arabic, egg).",
            "Make pens from reeds, quills, or sharpened sticks.",
            "Produce paper from plant fiber pulp, or use birch bark, clay tablets, or slate.",
            "Standardize spelling and abbreviations for official records.",
        ],
        "warnings": ["Ink fades over time—use carbon-based inks for permanence.", "Damp storage destroys paper—keep records dry and ventilated."],
        "related_entries": ["l5-communication-systems-basics", "l5-governance-record-keeping", "l5-edu-library-preservation"],
        "sources": ["openstax-intro-business-governance"],
    },
    {
        "id": "l5-comm-radio-operation",
        "title": "Radio Operation: Basic Protocols and Frequencies",
        "subtopic": "communication",
        "tags": ["communication", "radio", "electronics", "frequencies"],
        "summary": "Operating and maintaining radio equipment for reliable long-distance electronic communication.",
        "steps": [
            "Learn standard radio protocols: call signs, phonetic alphabet, brevity codes.",
            "Understand frequency bands: HF (3-30 MHz) for long range, VHF/UHF for local.",
            "Establish scheduled contact times (skeds) to conserve battery power.",
            "Build simple antennas: dipole for HF, ground-plane for VHF.",
            "Maintain equipment: protect from moisture, check connections, conserve batteries.",
        ],
        "warnings": ["Radio transmissions reveal your location—use sparingly in hostile situations.", "Atmospheric conditions affect HF propagation—have backup communication plans."],
        "related_entries": ["l5-communication-systems-basics", "l5-comm-encryption-basics", "l5-comm-signal-methods"],
        "sources": ["army-tm-electrical-basics"],
    },
    {
        "id": "l5-comm-encryption-basics",
        "title": "Encryption Basics: Simple Ciphers for Secure Messaging",
        "subtopic": "communication",
        "tags": ["communication", "encryption", "cipher", "security"],
        "summary": "Simple cipher methods for protecting sensitive communications from interception.",
        "steps": [
            "Use substitution ciphers (Caesar shift) for basic privacy; easy but breakable.",
            "Use transposition ciphers: rearrange letter positions using a keyword grid.",
            "Combine substitution + transposition for stronger encryption.",
            "One-time pad: use a random key as long as the message for unbreakable encryption.",
            "Pre-distribute codebooks to trusted parties; destroy after use.",
        ],
        "warnings": ["Simple ciphers are breakable by frequency analysis—don't rely on them for critical secrets.", "Key distribution is the hardest problem—protect keys physically."],
        "related_entries": ["l5-communication-systems-basics", "l5-comm-radio-operation", "l5-comm-messenger-networks"],
        "sources": ["army-land-navigation-fm-3-25-26"],
    },
    {
        "id": "l5-comm-messenger-networks",
        "title": "Messenger Networks: Relay and Courier Systems",
        "subtopic": "communication",
        "tags": ["communication", "messenger", "courier", "relay"],
        "summary": "Organizing reliable human messenger and relay networks for communication across distances.",
        "steps": [
            "Establish relay stations at intervals matching a runner's/rider's sustainable range.",
            "Use sealed, tamper-evident message containers.",
            "Implement authentication tokens so recipients can verify messenger identity.",
            "Maintain backup routes in case primary paths are compromised.",
            "Log all messages sent and received for accountability.",
        ],
        "warnings": ["Messengers can be intercepted—use encryption for sensitive content.", "Single points of failure in relay chains disable the whole network."],
        "related_entries": ["l5-communication-systems-basics", "l5-comm-encryption-basics", "l5-comm-signal-methods"],
        "sources": ["army-land-navigation-fm-3-25-26"],
    },
    # NAVIGATION
    {
        "id": "l5-nav-compass-construction",
        "title": "Compass Construction: Making a Magnetic Compass",
        "subtopic": "navigation",
        "tags": ["navigation", "compass", "magnetic", "direction"],
        "summary": "Building a functional magnetic compass from salvaged materials for direction finding.",
        "steps": [
            "Find a magnetizable needle, pin, or thin steel wire.",
            "Magnetize by stroking repeatedly in one direction with a magnet or by induction.",
            "Float the needle on a small leaf or cork in still water.",
            "The needle aligns north-south; mark the north-seeking end.",
            "Calibrate against known landmarks or celestial observations.",
        ],
        "warnings": ["Metal objects and electronics near the compass cause deviation.", "Magnetic north differs from true north—learn local declination."],
        "related_entries": ["l5-map-reading-basics", "l5-celestial-navigation-basics", "l5-nav-dead-reckoning"],
        "sources": ["army-land-navigation-fm-3-25-26", "bsa-handbook"],
    },
    {
        "id": "l5-nav-dead-reckoning",
        "title": "Dead Reckoning: Pace Counting and Direction Tracking",
        "subtopic": "navigation",
        "tags": ["navigation", "dead_reckoning", "pace_count", "tracking"],
        "summary": "Navigating by tracking direction and distance traveled from a known starting point.",
        "steps": [
            "Calibrate your pace count: walk 100m on flat ground, count double-steps.",
            "Use a compass bearing and walk a set number of paces to travel known distances.",
            "Record each leg: bearing, pace count, and terrain notes.",
            "Adjust pace count for slope (uphill = shorter paces) and terrain (brush = more paces).",
            "Cross-check position with terrain features whenever possible.",
        ],
        "warnings": ["Errors accumulate with distance—verify position frequently.", "Detours around obstacles must be carefully tracked to avoid drift."],
        "related_entries": ["l5-map-reading-basics", "l5-nav-compass-construction", "l5-math-measurement-systems"],
        "sources": ["army-land-navigation-fm-3-25-26"],
    },
    {
        "id": "l5-nav-river-and-terrain",
        "title": "River and Terrain Navigation: Using Water Features for Orientation",
        "subtopic": "navigation",
        "tags": ["navigation", "terrain", "rivers", "orientation"],
        "summary": "Using rivers, ridgelines, and terrain features as natural navigation aids.",
        "steps": [
            "Rivers flow downhill to larger water bodies—follow downstream to find settlements.",
            "Use ridgelines for vantage points to identify landmarks and plan routes.",
            "Read terrain: valleys funnel travel, saddles provide passes between peaks.",
            "Note vegetation patterns: different growth on north vs. south slopes.",
            "Use terrain association: match surrounding features to map to confirm position.",
        ],
        "warnings": ["Following rivers into gorges or rapids can be dangerous—scout ahead.", "Terrain features can look similar—use multiple landmarks for confirmation."],
        "related_entries": ["l5-map-reading-basics", "l5-nav-dead-reckoning", "l5-nav-weather-forecasting"],
        "sources": ["army-land-navigation-fm-3-25-26", "bsa-handbook"],
    },
    {
        "id": "l5-nav-weather-forecasting",
        "title": "Weather Forecasting: Cloud Reading and Barometric Signs",
        "subtopic": "navigation",
        "tags": ["navigation", "weather", "clouds", "forecasting"],
        "summary": "Predicting weather changes using cloud types, wind shifts, and natural indicators.",
        "steps": [
            "Learn cloud types: cirrus (high, fair) → cirrostratus (halo) → approaching front.",
            "Cumulus building vertically (cumulonimbus) signals thunderstorms in 2-4 hours.",
            "Wind shifting clockwise (veering) often means improving weather; counter-clockwise (backing) means deteriorating.",
            "Observe animal behavior: birds flying low, insects staying near ground suggest low pressure.",
            "Build a simple barometer: sealed jar with water tube—rising water = falling pressure = incoming storm.",
        ],
        "warnings": ["Local terrain (mountains, coasts) modifies large-scale weather patterns.", "Don't rely on single indicators—use multiple signs for reliable forecasts."],
        "related_entries": ["l5-map-reading-basics", "l5-nav-river-and-terrain", "l5-nav-time-keeping"],
        "sources": ["noaa-celestial-navigation", "bsa-handbook"],
    },
    {
        "id": "l5-nav-time-keeping",
        "title": "Time Keeping: Sundials and Simple Clocks",
        "subtopic": "navigation",
        "tags": ["navigation", "time", "sundial", "clocks"],
        "summary": "Measuring and tracking time using shadow sticks, sundials, and simple mechanical clocks.",
        "steps": [
            "Shadow stick method: plant vertical stick, mark shadow tip at intervals to find east-west line and solar noon.",
            "Build a simple sundial: angle the gnomon to your latitude, mark hour lines.",
            "Use water clocks (clepsydra) for consistent timing regardless of weather.",
            "Construct candle clocks with marked intervals for nighttime timing.",
            "Synchronize community time using solar noon (shortest shadow) as daily reference.",
        ],
        "warnings": ["Sundials show solar time, which varies from clock time seasonally.", "Water clocks need consistent water temperature for accuracy."],
        "related_entries": ["l5-celestial-navigation-basics", "l5-nav-compass-construction", "l5-math-trigonometry"],
        "sources": ["noaa-celestial-navigation", "openstax-college-physics"],
    },
    # EDUCATION
    {
        "id": "l5-edu-teaching-methods",
        "title": "Teaching Methods: Effective Knowledge Transfer Techniques",
        "subtopic": "education",
        "tags": ["education", "teaching", "learning", "pedagogy"],
        "summary": "Practical teaching techniques for transferring knowledge and skills in resource-limited settings.",
        "steps": [
            "Explain concepts verbally, then demonstrate physically (tell-show-do).",
            "Have learners practice immediately with guided feedback.",
            "Use analogies connecting new concepts to familiar experiences.",
            "Teach in small groups (5-8) for optimal engagement.",
            "Test retention through practical application, not just recitation.",
        ],
        "warnings": ["Skipping practice leads to poor retention—always include hands-on work.", "Adjust pace to slowest critical learner—lives may depend on their competence."],
        "related_entries": ["l5-edu-apprenticeship-systems", "l5-edu-scientific-method", "l5-governance-principles"],
        "sources": ["openstax-intro-business-governance"],
    },
    {
        "id": "l5-edu-library-preservation",
        "title": "Library Preservation: Book and Document Conservation",
        "subtopic": "education",
        "tags": ["education", "library", "preservation", "books"],
        "summary": "Protecting and preserving written knowledge for long-term community access.",
        "steps": [
            "Store books in cool, dry, ventilated spaces away from sunlight.",
            "Control pests with cedar, lavender, or diatomaceous earth—never chemicals near paper.",
            "Repair torn pages with rice paste adhesive and thin tissue.",
            "Copy deteriorating texts by hand before they become illegible.",
            "Prioritize preservation: technical manuals and reference works first.",
        ],
        "warnings": ["Mold destroys books rapidly—isolate and dry affected items immediately.", "Fire is the greatest threat—maintain separation and fire suppression near archives."],
        "related_entries": ["l5-comm-writing-systems", "l5-governance-record-keeping", "l5-edu-teaching-methods"],
        "sources": ["openstax-intro-business-governance"],
    },
    {
        "id": "l5-edu-apprenticeship-systems",
        "title": "Apprenticeship Systems: Skill Transfer Frameworks",
        "subtopic": "education",
        "tags": ["education", "apprenticeship", "skills", "training"],
        "summary": "Structured apprenticeship programs for transferring critical trade skills across generations.",
        "steps": [
            "Identify critical skills that must be preserved (smithing, medicine, agriculture, etc.).",
            "Pair each master practitioner with 1-3 apprentices.",
            "Structure learning progression: observe → assist → perform under supervision → solo.",
            "Set milestones and practical tests for advancement.",
            "Require journeyman apprentices to teach beginners (teaching reinforces learning).",
        ],
        "warnings": ["Single points of failure: if only one person knows a skill, train backups urgently.", "Apprenticeships take years—start training before current masters age out."],
        "related_entries": ["l5-edu-teaching-methods", "l5-edu-scientific-method", "l5-governance-principles"],
        "sources": ["openstax-intro-business-governance"],
    },
    {
        "id": "l5-edu-scientific-method",
        "title": "Scientific Method: Observation, Hypothesis, and Testing",
        "subtopic": "education",
        "tags": ["education", "science", "method", "experimentation"],
        "summary": "Applying systematic observation and experimentation to solve problems and improve techniques.",
        "steps": [
            "Observe a phenomenon or problem carefully; record detailed notes.",
            "Form a hypothesis: a testable explanation for what you observed.",
            "Design a simple experiment: change one variable, keep others constant.",
            "Record results honestly, including failures and unexpected outcomes.",
            "Share findings with the community; repeat experiments to verify.",
        ],
        "warnings": ["Confirmation bias: don't ignore results that contradict your hypothesis.", "Anecdotes are not evidence—require repeatable results."],
        "related_entries": ["l5-edu-teaching-methods", "l5-math-statistics-basics", "l5-governance-record-keeping"],
        "sources": ["openstax-biology-2e", "openstax-college-physics"],
    },
    # HEALTH & SANITATION
    {
        "id": "l5-health-sanitation-systems",
        "title": "Sanitation Systems: Latrine Design and Waste Management",
        "subtopic": "public_health",
        "tags": ["public_health", "sanitation", "latrine", "waste"],
        "summary": "Designing and building sanitation systems to prevent disease from human waste.",
        "steps": [
            "Site latrines 30+ meters from water sources and downhill from wells.",
            "Dig pit latrines at least 2 meters deep with stable, lined walls.",
            "Build a slab cover with a hole and a lid to reduce flies and odor.",
            "Add ash, lime, or soil after each use to accelerate decomposition.",
            "When pits are 0.5m from full, cap with soil and dig a new pit.",
        ],
        "warnings": ["Fecal contamination of water is the #1 killer in post-collapse scenarios.", "Never use fresh human waste as fertilizer—compost for 1+ year first."],
        "related_entries": ["l5-health-disease-prevention", "l5-health-water-infrastructure", "l5-governance-principles"],
        "sources": ["who-household-water-treatment", "cdc-water-emergency"],
    },
    {
        "id": "l5-health-disease-prevention",
        "title": "Disease Prevention: Quarantine and Hygiene Principles",
        "subtopic": "public_health",
        "tags": ["public_health", "disease", "quarantine", "hygiene"],
        "summary": "Basic epidemiological principles for preventing disease outbreaks in community settings.",
        "steps": [
            "Enforce handwashing with soap or ash before eating and after latrine use.",
            "Isolate sick individuals promptly; designate a quarantine area.",
            "Boil or treat all drinking water from uncertain sources.",
            "Bury or burn animal carcasses and medical waste away from living areas.",
            "Track illness patterns to identify outbreaks early.",
        ],
        "warnings": ["Diarrheal disease kills through dehydration—treat with oral rehydration solution immediately.", "Airborne diseases require physical separation, not just hygiene."],
        "related_entries": ["l5-health-sanitation-systems", "l5-health-water-infrastructure", "l5-governance-record-keeping"],
        "sources": ["who-basic-emergency-care-2018", "cdc-water-emergency"],
    },
    {
        "id": "l5-health-water-infrastructure",
        "title": "Water Infrastructure: Community Water System Design",
        "subtopic": "public_health",
        "tags": ["public_health", "water", "infrastructure", "purification"],
        "summary": "Designing community-scale water collection, treatment, and distribution systems.",
        "steps": [
            "Identify water sources: springs, wells, rainwater, surface water (in order of preference).",
            "Protect spring sources with a spring box to prevent contamination.",
            "Build slow sand filters for community water treatment (effective, low-tech).",
            "Design gravity-fed distribution from elevated storage tanks.",
            "Establish water testing routines and maintenance schedules.",
        ],
        "warnings": ["Untreated surface water carries parasites, bacteria, and viruses.", "Pipe systems require ongoing maintenance—train local technicians."],
        "related_entries": ["l5-health-sanitation-systems", "l5-health-disease-prevention", "l5-mech-fluid-mechanics-basics"],
        "sources": ["who-household-water-treatment", "cdc-water-emergency", "fema-water-storage"],
    },
    {
        "id": "l5-health-dental-care-basics",
        "title": "Dental Care Basics: Preventive Dental Hygiene",
        "subtopic": "public_health",
        "tags": ["public_health", "dental", "hygiene", "prevention"],
        "summary": "Preventive dental care practices to maintain oral health without modern dentistry.",
        "steps": [
            "Brush teeth after meals using frayed twig (miswak/neem), charcoal powder, or baking soda.",
            "Floss with thin thread, sinew, or plant fiber between teeth daily.",
            "Rinse mouth with salt water to reduce bacteria and inflammation.",
            "Avoid excessive sugar and acidic foods that erode enamel.",
            "Address toothaches early with clove oil (eugenol) for pain relief.",
        ],
        "warnings": ["Dental infections can become life-threatening—don't ignore persistent pain or swelling.", "Extraction without training risks broken jaw or uncontrolled bleeding."],
        "related_entries": ["l5-health-disease-prevention", "l5-health-sanitation-systems"],
        "sources": ["who-basic-emergency-care-2018"],
    },
]

def generate_entry(entry):
    front_matter = {
        "id": entry["id"],
        "title": entry["title"],
        "category": "L5_civilization_memory",
        "subtopic": entry["subtopic"],
        "tags": entry["tags"],
        "region_relevance": ["global"],
        "summary": entry["summary"],
        "steps": entry["steps"],
        "warnings": entry["warnings"],
        "related_entries": entry["related_entries"],
        "sources": entry["sources"],
        "last_verified": "2026-02-18",
        "confidence": "high",
        "offline_assets": [],
    }
    
    import yaml
    yaml_str = yaml.safe_dump(front_matter, default_flow_style=False, sort_keys=False, allow_unicode=True)
    
    steps_md = "\n".join(f"{i+1}. {s}" for i, s in enumerate(entry["steps"]))
    warnings_md = "\n".join(f"- {w}" for w in entry["warnings"])
    
    content = f"""---
{yaml_str}---

## Overview
{entry["summary"]}

## Step-by-step
{steps_md}

## Warnings
{warnings_md}
"""
    return content

os.makedirs(OUTPUT_DIR, exist_ok=True)
count = 0
for entry in ENTRIES:
    path = os.path.join(OUTPUT_DIR, f"{entry['id']}.md")
    content = generate_entry(entry)
    with open(path, "w") as f:
        f.write(content)
    count += 1
    print(f"  ✓ {entry['id']}")

print(f"\nGenerated {count} entries.")
