#!/usr/bin/env python3
"""BATCH 3: Fish (5), game birds (3), medicinals (5), crisis scenarios (10) = 23 entries → 322 total"""
import yaml
from pathlib import Path

OUT_L1 = Path(__file__).resolve().parents[1] / "data" / "entries" / "L1_immediate_survival"
OUT_L2 = Path(__file__).resolve().parents[1] / "data" / "entries" / "L2_food_biology"
OUT_L5 = Path(__file__).resolve().parents[1] / "data" / "entries" / "L5_community_knowledge"
for d in [OUT_L1, OUT_L2, OUT_L5]: d.mkdir(parents=True, exist_ok=True)
TODAY = "2026-02-18"

def w(e, out_dir):
    md_path = out_dir / f"{e['id']}.md"
    fm = yaml.dump(e, default_flow_style=False, allow_unicode=True, sort_keys=False, width=200)
    md_path.write_text(f"---\n{fm}---\n\n# {e['title']}\n\n{e['summary']}\n")
    print(f"  ✓ {e['id']}")

E = []

# === FISH (5 common edible species) ===
E.append({'id':'l2-fish-trout-identification','title':'Trout — Identification & Field Dressing','category':'L2_food_biology','subtopic':'hunting_fishing','tags':['trout','fish','freshwater','survival-fishing'],'region_relevance':['temperate','boreal','mountainous'],'confidence':'high','sources':['usda-food-safety'],'related_entries':['l2-food-fish-preservation'],'last_verified':TODAY,'summary':'Trout (rainbow, brook, brown, cutthroat) are widespread freshwater fish in cold streams and lakes. Excellent eating, relatively easy to catch. Must be cleaned and cooked thoroughly. Learn to identify by coloration and habitat.','warnings':['Raw or undercooked fish can carry parasites - cook to 145F internal temp','Trout from polluted waters accumulate toxins - avoid fish downstream of industry','Brook trout are native only in eastern North America - introduced elsewhere','Some waters require fishing licenses even in survival situations (check local laws)'],'steps':['IDENTIFICATION: Body shape: streamlined, torpedo-shaped. Size: 8-30 inches. RAINBOW TROUT: pink stripe along side, black spots on back/tail. BROOK TROUT: worm-like markings on back, white edges on fins, red belly. BROWN TROUT: brown/gold with red/black spots, white-edged spots. CUTTHROAT: red slash under jaw. HABITAT: cold streams, rivers, mountain lakes.','FIELD DRESSING: (1) Cut from vent (anus) to gills. (2) Remove guts (discard or use as bait). (3) Cut out gills. (4) Rinse cavity with clean water. (5) Optional: remove head and tail. Dressed fish can be cooked immediately or preserved.','COOKING: (1) Grilling: gut fish, stuff cavity with herbs/salt, wrap in leaves or foil, cook over coals 5-10 min per side. (2) Frying: fillet, coat in flour, fry in fat. (3) Boiling: add to stew. (4) Smoking: see preservation entry. Internal temp 145F (flesh flakes easily).','NUTRITION: High protein (20g per 4oz), omega-3 fatty acids, vitamin D, B vitamins. Excellent survival food.']})

E.append({'id':'l2-fish-bass-identification','title':'Bass — Largemouth & Smallmouth Identification','category':'L2_food_biology','subtopic':'hunting_fishing','tags':['bass','fish','freshwater','survival-fishing'],'region_relevance':['temperate','north-america'],'confidence':'high','sources':['usda-food-safety'],'related_entries':['l2-fish-trout-identification'],'last_verified':TODAY,'summary':'Bass (Micropterus species) are common predatory fish in lakes, ponds, and rivers. Largemouth and smallmouth bass are both edible and fight hard on the line. Good eating but bony.','warnings':['Bass from warm/stagnant water can taste muddy - cold, flowing water produces better flavor','Large bass (over 5 lbs) can accumulate mercury - smaller fish are safer','Remove lateral line (dark meat along side) to reduce strong flavor'],'steps':['IDENTIFICATION: LARGEMOUTH BASS: large mouth extends past eye, dark horizontal stripe along side, greenish body, 10-20 inches common. SMALLMOUTH BASS: mouth ends at eye, vertical bars on side, bronze/brown body. HABITAT: Largemouth in warm weedy ponds/lakes. Smallmouth in cooler rocky streams/lakes.','FIELD DRESSING: Same as trout - gut, remove gills, rinse. Bass are scalier than trout - scrape scales off or fillet to remove skin.','FILLETING: (1) Cut behind gills down to backbone. (2) Slide knife along backbone toward tail. (3) Remove rib bones. (4) Remove skin if desired. (5) Remove lateral line (dark meat).','COOKING: Fry fillets, bake, grill. Firm white meat. Cook to 145F. Mild flavor when prepared well.']})

E.append({'id':'l2-fish-catfish-identification','title':'Catfish — Bottom Feeder Survival Fish','category':'L2_food_biology','subtopic':'hunting_fishing','tags':['catfish','fish','freshwater','survival-fishing'],'region_relevance':['temperate','global'],'confidence':'high','sources':['usda-food-safety'],'related_entries':['l2-fish-bass-identification'],'last_verified':TODAY,'summary':'Catfish (Ictalurus and related species) are bottom-dwelling fish with whisker-like barbels. Easy to catch (scavengers, eat almost anything). No scales but have tough skin. Excellent eating when cleaned properly.','warnings':['Catfish have sharp spines on dorsal and pectoral fins - puncture wounds can become infected, handle carefully','Bottom feeders from polluted water accumulate toxins - avoid catfish from industrial/urban waters','Skin is tough and slimy - requires pliers or skinning technique'],'steps':['IDENTIFICATION: Flattened head, 8 barbels (whiskers), no scales, smooth slimy skin. Dorsal and pectoral fins have sharp spines. Color varies (brown, yellow, gray). Size: 1-50 lbs. HABITAT: rivers, lakes, ponds, muddy bottoms. Worldwide distribution.','FIELD DRESSING: (1) Kill immediately (nail through head). (2) Gut fish. (3) SKINNING: Catfish must be skinned (no scales). Cut around head and along dorsal fin. Use pliers to peel skin toward tail. Or nail head to tree, pull skin with pliers.','REMOVING SPINES: Cut off dorsal and pectoral fins (spines are embedded in fins, not the body).','COOKING: Fillet or cook whole. Firm white meat, mild flavor. Fry (Southern classic), bake, or smoke. Cook to 145F.','NUTRITION: High protein, low fat. Firm texture makes it good for stews.']})

E.append({'id':'l2-fish-panfish-identification','title':'Panfish — Bluegill, Sunfish, Crappie','category':'L2_food_biology','subtopic':'hunting_fishing','tags':['panfish','bluegill','sunfish','crappie','survival-fishing'],'region_relevance':['temperate','north-america'],'confidence':'high','sources':['usda-food-safety'],'related_entries':['l2-fish-trout-identification'],'last_verified':TODAY,'summary':'Panfish (bluegill, sunfish, crappie) are small fish (4-10 inches) that are easy to catch in ponds and lakes. Abundant, bite readily, good eating. Small but numerous - catch dozens for a meal.','warnings':['Small size means more work per pound of meat - but easy to catch in quantity','Bony - eat carefully or pressure-cook to soften bones','Panfish from warm stagnant water can taste muddy'],'steps':['IDENTIFICATION: Small, flat-bodied fish. BLUEGILL: dark blue/black spot on gill cover, vertical bars on side, 6-10 inches. CRAPPIE: speckled pattern, paper-thin mouth, 8-12 inches. HABITAT: ponds, lakes, slow rivers. Near vegetation.','FIELD DRESSING: Gut and scale (small scales come off easily). Or fillet. Very little meat per fish.','COOKING: (1) Whole: gut, scale, fry in pan (eat around bones). (2) Fillet: small fillets, bread and fry. (3) Pressure cook: cooks bones soft, can eat entire fish. Mild, sweet flavor.','STRATEGY: Catch many small panfish rather than a few large fish - easier in survival scenario.']})

E.append({'id':'l2-fish-salmon-identification','title':'Salmon — Anadromous Fish Field Identification','category':'L2_food_biology','subtopic':'hunting_fishing','tags':['salmon','fish','anadromous','coastal','high-fat'],'region_relevance':['coastal','boreal','temperate'],'confidence':'high','sources':['usda-food-safety'],'related_entries':['l2-fish-trout-identification','l2-food-fish-smoking'],'last_verified':TODAY,'summary':'Salmon (Oncorhynchus and Salmo species) are anadromous fish (spawn in freshwater, live in ocean). Return to rivers in huge runs (seasonal). Extremely high in fat and calories - one of the best survival fish. Pacific salmon die after spawning.','warnings':['Spawning salmon (red coloration, hooked jaw) are edible but flesh quality declines rapidly after spawning - catch them early in run','Raw salmon can carry parasites - freeze at -4F for 7 days or cook to 145F','Pacific salmon species return at different times - learn local run schedules'],'steps':['IDENTIFICATION: Large fish (12-40 inches). SPECIES (Pacific): Chinook (king) - largest, black gums. Coho (silver) - metallic blue back. Sockeye - bright red in spawning color. Pink - smallest, humpback. ATLANTIC SALMON: spots on back. HABITAT: Coastal rivers during spawning runs (summer-fall).','FIELD DRESSING: Same as trout but larger. Gut, remove gills. Save roe (eggs) - edible and nutritious.','SMOKING: Salmon is ideal for smoking (high fat content). See smoking entry. Smoked salmon lasts weeks.','COOKING: Grill, bake, poach, smoke. Rich, oily, flavorful. High calorie.','NUTRITION: Very high in omega-3 fatty acids, protein, vitamin D, calories (200+ cal per 4oz). One salmon provides days of food.']})

# === GAME BIRDS (3 species) ===
E.append({'id':'l2-food-wild-turkey-processing','title':'Wild Turkey — Field Dressing & Cooking','category':'L2_food_biology','subtopic':'hunting_fishing','tags':['wild-turkey','game-bird','poultry','survival-hunting'],'region_relevance':['temperate','north-america'],'confidence':'high','sources':['usda-food-safety'],'related_entries':['l2-food-meat-preservation'],'last_verified':TODAY,'summary':'Wild turkey (Meleagris gallopavo) is a large game bird (10-25 lbs). Excellent eating, similar to domestic turkey but leaner. Provides substantial meat. Must be plucked or skinned, gutted, and cooked thoroughly.','warnings':['Wild turkeys can carry Salmonella and other bacteria - cook to 165F internal temp','Plucking is very time-consuming - skinning is faster but removes fat and flavor','Harvest regulations vary - legal hunting in some areas, protected in others','Turkeys are wary and difficult to hunt without experience'],'steps':['FIELD DRESSING: (1) Cut around vent. (2) Cut up to breastbone. (3) Reach in, pull out internal organs. (4) Remove crop (food pouch in neck). (5) Rinse cavity. Optional: save heart, liver, gizzard (edible).','PLUCKING: Dip bird in hot water (150-160F) for 30-60 seconds. Pluck feathers (pull in direction they grow). Time-consuming. OR SKINNING: Cut skin at breast, peel back, remove entire skin. Faster but removes flavor and fat.','COOKING: (1) Roast whole (like domestic turkey) - stuff cavity with herbs, roast 3-4 hours at 325F. (2) Quarter and stew. (3) Breast meat can be sliced and fried. Internal temp 165F. Meat is darker and leaner than domestic turkey.','NUTRITION: High protein, low fat (leaner than domestic poultry). Large bird provides 10-15 lbs of meat.']})

E.append({'id':'l2-food-duck-field-dressing','title':'Ducks — Waterfowl Field Processing','category':'L2_food_biology','subtopic':'hunting_fishing','tags':['duck','waterfowl','game-bird','survival-hunting'],'region_relevance':['temperate','global'],'confidence':'high','sources':['usda-food-safety'],'related_entries':['l2-food-wild-turkey-processing'],'last_verified':TODAY,'summary':'Wild ducks (mallard, teal, wood duck, etc.) are common waterfowl. Dark, rich meat (high in fat compared to turkey). Pluck or skin, gut, cook thoroughly. Excellent roasted or smoked.','warnings':['Ducks must be cooked to 165F - dark meat looks rare even when fully cooked','Plucking ducks is difficult (feathers are waterproof) - requires hot water and patience','Some ducks taste fishy if they feed on fish - corn-fed ducks taste better','Protected species exist - learn to identify legal species vs protected'],'steps':['FIELD DRESSING: (1) Cut around vent. (2) Open body cavity, remove organs. (3) Remove crop. Rinse. Save heart/liver.','PLUCKING: Very difficult due to waterproof feathers. Scald in 140-150F water for 1-2 min, pluck immediately. Down (fine feathers) is hardest to remove. OR SKINNING: Faster. Cut skin, peel away. Removes fat layer.','BREASTING: Alternative to full plucking. Cut along breastbone, peel back skin, carve out breast meat. Discard rest (or save legs/thighs). Fast method for survival.','COOKING: (1) Roast whole (stuff cavity, roast at 350F for 1-2 hours). (2) Breast fillets pan-seared (medium-rare to medium - dark meat). (3) Confit (slow-cook in fat). Rich, gamey flavor.','NUTRITION: High in fat and protein, iron, B vitamins. Calorie-dense.']})

E.append({'id':'l2-food-goose-field-processing','title':'Geese — Large Waterfowl Processing','category':'L2_food_biology','subtopic':'hunting_fishing','tags':['goose','waterfowl','game-bird','survival-hunting'],'region_relevance':['temperate','boreal','global'],'confidence':'high','sources':['usda-food-safety'],'related_entries':['l2-food-duck-field-dressing'],'last_verified':TODAY,'summary':'Wild geese (Canada goose, snow goose, etc.) are large waterfowl (6-14 lbs). Dark, rich meat similar to duck but larger. Plucking is extremely difficult - skinning or breasting recommended for field use.','warnings':['Geese are tough to pluck - skinning is more practical','Cook to 165F internal temp','Some geese taste very gamey (grass-fed) - marinate to reduce strong flavor','Geese migrate seasonally - availability varies by time and location'],'steps':['FIELD DRESSING: Same as duck/turkey. Gut, rinse, optional plucking/skinning.','PLUCKING VS BREASTING: Full plucking takes hours. PRACTICAL: breast the bird (carve out breast meat, save legs/thighs, discard rest). Fast and yields most of the meat.','COOKING: (1) Roast whole (stuff, roast 2-3 hours at 325-350F). (2) Breast meat sliced and pan-seared. (3) Slow-cook tough cuts (legs/thighs) in stew. Dark, rich, fatty meat. Strong flavor.','PRESERVING: Geese are fatty - excellent for smoking or rendering fat (use for cooking). Smoked goose lasts weeks.','NUTRITION: High fat, high protein, calories. One goose provides substantial food (4-8 lbs meat).']})

for e in E: 
    if 'L2' in e['category']: w(e, OUT_L2)
    elif 'L1' in e['category']: w(e, OUT_L1)
    else: w(e, OUT_L5)

print(f"\n=== Batch 3 part 1 complete: {len(E)} entries (fish + game birds) ===")
print("Continuing with medicinals and crisis scenarios...")
