#!/usr/bin/env python3
"""Generate all L2 Food & Biology expansion entries."""
import datetime as dt
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[1]
ENTRIES = ROOT / "data" / "entries" / "L2_food_biology"
TODAY = dt.date.today().isoformat()

SEEDS = [
    # ── EDIBLE PLANTS ──
    dict(id="l2-plants-dandelion", title="Dandelion (Taraxacum officinale)", subtopic="edible_plants",
         tags=["dandelion","edible","greens","root","global"], region_relevance=["global","temperate"],
         summary="Ubiquitous perennial weed; all parts edible — leaves, flowers, and roots. High in vitamins A, C, K, and iron. One of the safest beginner foraging plants.",
         steps=["Identify by rosette of deeply toothed leaves, hollow stem, single yellow composite flower, milky latex sap.",
                "Harvest young leaves before flowering for mildest flavor.",
                "Flowers can be eaten raw, battered and fried, or infused.",
                "Roots can be roasted as coffee substitute or boiled as vegetable.",
                "Wash thoroughly; avoid roadsides and treated lawns."],
         warnings=["Avoid areas treated with herbicides or pesticides.","Cat's ear (Hypochaeris radicata) is a common lookalike — has branched stems and hairy leaves, but is also edible."],
         related_entries=["l2-plants-identification-protocol","l2-plants-clover","l2-plants-chickweed"],
         sources=["peterson-field-guides-edible-wild-plants","usda-plants-database"], confidence="high"),

    dict(id="l2-plants-cattail", title="Cattail (Typha latifolia)", subtopic="edible_plants",
         tags=["cattail","wetland","starch","pollen"], region_relevance=["global","temperate","tropical"],
         summary="Wetland staple plant; nearly every part is edible across seasons. Rhizomes provide starch, shoots are eaten like asparagus, pollen is a protein-rich flour supplement.",
         steps=["Identify by tall linear leaves, distinctive brown cylindrical seed head, and wetland habitat.",
                "Spring: harvest young shoots when under 60cm — peel and eat raw or cooked.",
                "Early summer: collect green flower spikes, boil like corn.",
                "Mid-summer: shake pollen from male spike into bag for flour.",
                "Fall/winter: dig rhizomes, wash, crush in water, settle starch."],
         warnings=["Confirm wetland is not contaminated with industrial runoff or sewage.","Wild iris (toxic) grows in similar habitats — iris leaves have a distinct midrib and fan arrangement vs cattail's linear wrap."],
         related_entries=["l2-plants-identification-protocol","l2-plants-watercress","l2-plants-burdock"],
         sources=["peterson-field-guides-edible-wild-plants","usda-plants-database","extension-edible-plants"], confidence="high"),

    dict(id="l2-plants-plantain-broadleaf", title="Broadleaf Plantain (Plantago major)", subtopic="edible_plants",
         tags=["plantain","wound-herb","greens","global"], region_relevance=["global","temperate"],
         summary="Common lawn and trailside plant with edible leaves and medicinal wound-care tradition. Young leaves eaten raw or cooked; older leaves are fibrous but still nutritious.",
         steps=["Identify by basal rosette of broad oval leaves with prominent parallel veins and a central flower spike.",
                "Harvest young leaves for salads; older leaves are better cooked.",
                "Seeds can be collected and ground as a fiber supplement (related to psyllium).",
                "Poultice of crushed leaves traditionally applied to insect stings and minor wounds."],
         warnings=["Not the same as banana-family plantain.","Avoid harvesting from treated lawns."],
         related_entries=["l2-plants-dandelion","l2-plants-clover","l2-plants-identification-protocol"],
         sources=["peterson-field-guides-edible-wild-plants","usda-plants-database"], confidence="high"),

    dict(id="l2-plants-clover", title="Clover (Trifolium spp.)", subtopic="edible_plants",
         tags=["clover","flowers","tea","nitrogen-fixer"], region_relevance=["global","temperate"],
         summary="Extremely common legume; flowers and young leaves are edible raw or cooked. Dried flower heads make a mild tea. Also a nitrogen-fixing cover crop.",
         steps=["Identify by trifoliate leaves with light chevron markings and round flower heads (white or red).",
                "Eat young leaves raw in salads or cooked.",
                "Dry flower heads for tea (steep 10-15 minutes).",
                "Avoid large quantities raw — contains isoflavones and can cause bloating."],
         warnings=["Large quantities may cause digestive discomfort.","Avoid clover from sprayed fields."],
         related_entries=["l2-plants-dandelion","l2-plants-chickweed","l2-plants-wood-sorrel"],
         sources=["peterson-field-guides-edible-wild-plants","usda-plants-database"], confidence="high"),

    dict(id="l2-plants-chickweed", title="Chickweed (Stellaria media)", subtopic="edible_plants",
         tags=["chickweed","mild-green","salad","cool-season"], region_relevance=["global","temperate"],
         summary="Mild-flavored cool-season green found worldwide in disturbed soils. Excellent raw salad plant with good vitamin C content.",
         steps=["Identify by small opposite leaves, single line of hairs along stem (alternating sides), tiny white star-shaped flowers with deeply cleft petals.",
                "Harvest above-ground portions; snip with scissors.",
                "Best eaten raw — mild, slightly sweet.",
                "Cooks down significantly; add at end of cooking."],
         warnings=["Spurge (Euphorbia) can be confused — check for milky sap (chickweed has clear sap).","Mouse-ear chickweed (Cerastium) is also edible but hairy."],
         related_entries=["l2-plants-clover","l2-plants-lambs-quarters","l2-plants-purslane"],
         sources=["peterson-field-guides-edible-wild-plants","usda-plants-database"], confidence="high"),

    dict(id="l2-plants-amaranth", title="Amaranth (Amaranthus spp.)", subtopic="edible_plants",
         tags=["amaranth","grain","greens","protein","warm-season"], region_relevance=["global","tropical","temperate"],
         summary="Dual-purpose plant providing both nutritious greens and protein-rich grain. Thrives in poor soils and heat. One of the most calorie-dense wild foods.",
         steps=["Identify by alternate simple leaves, dense flower spikes (often red/purple), tiny seeds.",
                "Harvest leaves when young for cooking like spinach.",
                "Collect seed heads when dry; thresh and winnow seeds.",
                "Seeds: toast lightly or grind into flour. High in lysine (rare in grains).",
                "Boil greens briefly to reduce oxalates."],
         warnings=["High oxalate content — cook before eating in quantity.","Pigweed species can accumulate nitrates from fertilized soil."],
         related_entries=["l2-plants-lambs-quarters","l2-plants-purslane","l2-nutrition-macros-basics"],
         sources=["peterson-field-guides-edible-wild-plants","usda-plants-database","extension-edible-plants"], confidence="high"),

    dict(id="l2-plants-lambs-quarters", title="Lamb's Quarters (Chenopodium album)", subtopic="edible_plants",
         tags=["lambs-quarters","spinach-substitute","greens","seeds"], region_relevance=["global","temperate"],
         summary="One of the best wild spinach substitutes. Extremely common garden weed with diamond-shaped leaves coated in white mealy powder. More nutritious than cultivated spinach.",
         steps=["Identify by diamond/goosefoot-shaped leaves with white powdery coating, especially on new growth.",
                "Harvest young leaves and tender tops.",
                "Cook like spinach — sauté, steam, or add to soups.",
                "Seeds are edible and can be ground to flour (related to quinoa)."],
         warnings=["Contains oxalic acid — cook to reduce; avoid if prone to kidney stones.","Can accumulate nitrates from fertilized soil."],
         related_entries=["l2-plants-amaranth","l2-plants-chickweed","l2-plants-stinging-nettle"],
         sources=["peterson-field-guides-edible-wild-plants","usda-plants-database"], confidence="high"),

    dict(id="l2-plants-wood-sorrel", title="Wood Sorrel (Oxalis spp.)", subtopic="edible_plants",
         tags=["wood-sorrel","oxalis","lemony","salad"], region_relevance=["global","temperate","tropical"],
         summary="Small clover-lookalike with heart-shaped leaflets and pleasant lemony flavor from oxalic acid. Excellent trail snack and salad addition in small quantities.",
         steps=["Identify by three heart-shaped (notched) leaflets — NOT round like clover. Five-petaled flowers (yellow, white, or pink).",
                "Eat leaves, flowers, and seed pods raw.",
                "Use as lemon substitute in cooking and drinks.",
                "Leaves fold down at night and in strong sun."],
         warnings=["Contains oxalic acid — eat in moderation, not as a staple.","Avoid large quantities if kidney stone prone."],
         related_entries=["l2-plants-clover","l2-plants-chickweed","l2-plants-dandelion"],
         sources=["peterson-field-guides-edible-wild-plants","usda-plants-database"], confidence="high"),

    dict(id="l2-plants-pine-needle-tea", title="Pine Needle Tea (Pinus spp.)", subtopic="edible_plants",
         tags=["pine","tea","vitamin-c","conifer","winter"], region_relevance=["global","temperate","boreal","alpine"],
         summary="Emergency vitamin C source available year-round in conifer forests. Fresh pine needles steeped in hot water produce a mildly resinous, citrusy tea.",
         steps=["Identify true pines by needles in bundled clusters (fascicles of 2, 3, or 5).",
                "Harvest fresh green needles; chop or bruise to release oils.",
                "Steep in hot (not boiling) water for 10-20 minutes.",
                "Strain and drink. Add sweetener if available."],
         warnings=["AVOID yew (Taxus), Norfolk Island pine, and Ponderosa pine — toxic.","Pregnant women should avoid pine needle tea (potential abortifacient).","Some cypress-family trees look similar — confirm true Pinus by fascicle bundles."],
         related_entries=["l2-plants-rose-hips","l2-plants-identification-protocol","l2-nutrition-deficiency-signs"],
         sources=["peterson-field-guides-edible-wild-plants","extension-edible-plants"], confidence="high"),

    dict(id="l2-plants-acorns", title="Acorns (Quercus spp.)", subtopic="edible_plants",
         tags=["acorns","oak","starch","leaching","fall"], region_relevance=["temperate","global"],
         summary="Abundant fall nut crop requiring tannin leaching before consumption. Once processed, acorns provide excellent starch and fat. White oak group has less tannin than red oak.",
         steps=["Collect mature fallen acorns; discard any with holes (weevil damage).",
                "Shell and chop or grind nutmeat.",
                "Leach tannins by soaking in multiple changes of water (cold water: days; hot water: hours).",
                "Test by tasting — should have no bitterness remaining.",
                "Dry and grind into flour, or use wet paste directly in recipes."],
         warnings=["Unleached acorns are very bitter and can cause nausea/kidney stress.","Red oak acorns require more leaching than white oak.","Proper leaching is non-negotiable."],
         related_entries=["l2-plants-amaranth","l2-plants-cattail","l2-nutrition-macros-basics"],
         sources=["peterson-field-guides-edible-wild-plants","usda-plants-database","extension-edible-plants"], confidence="high"),

    dict(id="l2-plants-purslane", title="Purslane (Portulaca oleracea)", subtopic="edible_plants",
         tags=["purslane","omega-3","succulent","summer"], region_relevance=["global","temperate","arid"],
         summary="Succulent garden weed and one of the richest plant sources of omega-3 fatty acids. Crunchy, slightly sour. Thrives in heat and poor soil.",
         steps=["Identify by thick succulent stems (often reddish), small paddle-shaped leaves, tiny yellow flowers.",
                "Harvest stems and leaves; entire above-ground plant is edible.",
                "Eat raw in salads or cook briefly (thickens soups like okra).",
                "Seeds are tiny but edible and nutritious."],
         warnings=["Spurge (Euphorbia) is a toxic lookalike — check for milky sap (purslane has clear sap) and round vs paddle leaves.","Contains oxalates — moderate consumption if kidney stone prone."],
         related_entries=["l2-plants-chickweed","l2-plants-lambs-quarters","l2-plants-amaranth"],
         sources=["peterson-field-guides-edible-wild-plants","usda-plants-database"], confidence="high"),

    dict(id="l2-plants-stinging-nettle", title="Stinging Nettle (Urtica dioica)", subtopic="edible_plants",
         tags=["nettle","nutritious","cooking-required","spring"], region_relevance=["global","temperate"],
         summary="Extremely nutritious green high in iron, calcium, and protein — but must be cooked or dried to neutralize stinging hairs. One of the most nutrient-dense wild foods.",
         steps=["Identify by opposite toothed leaves, square stem, and visible stinging hairs.",
                "Harvest with gloves — top 4-6 leaves of young spring plants.",
                "Cook by boiling, steaming, or sautéing (2+ minutes destroys sting).",
                "Dried nettle also loses sting and makes excellent tea.",
                "Cooking water can be drunk as nutritious broth."],
         warnings=["Handle ONLY with gloves until cooked — stinging hairs inject formic acid.","Do not eat raw.","Older plants develop cystoliths that may irritate kidneys — harvest young."],
         related_entries=["l2-plants-lambs-quarters","l2-plants-amaranth","l2-nutrition-deficiency-signs"],
         sources=["peterson-field-guides-edible-wild-plants","usda-plants-database","extension-edible-plants"], confidence="high"),

    dict(id="l2-plants-wild-garlic", title="Wild Garlic / Ramps (Allium spp.)", subtopic="edible_plants",
         tags=["allium","garlic","ramps","spring"], region_relevance=["temperate","boreal"],
         summary="Wild alliums (ramps, wild garlic, field garlic) provide pungent flavor and nutrition. Identified by strong garlic/onion smell when crushed — the smell test is the key safety check.",
         steps=["Crush a leaf — must smell distinctly of garlic/onion. No smell = not allium = potential poison.",
                "Identify ramps by broad elliptical leaves (1-2 per plant), red stem base, appearing in spring.",
                "Field garlic (A. vineale): thin hollow leaves, small bulb clusters.",
                "All parts edible: leaves, stems, bulbs. Use raw or cooked."],
         warnings=["CRITICAL: Lily of the valley (Convallaria) and death camas (Zigadenus) are deadly lookalikes — ALWAYS confirm garlic smell before eating.","Harvest sustainably — ramps are slow-growing. Take only one leaf per plant."],
         related_entries=["l2-plants-identification-protocol","l2-plants-stinging-nettle","l2-plants-burdock"],
         sources=["peterson-field-guides-edible-wild-plants","usda-plants-database"], confidence="high"),

    dict(id="l2-plants-burdock", title="Burdock (Arctium spp.)", subtopic="edible_plants",
         tags=["burdock","root-vegetable","biennial"], region_relevance=["temperate","global"],
         summary="Large biennial with edible taproot (gobo) and young stalks. First-year roots are tender and starchy. Widely cultivated in East Asian cuisine.",
         steps=["Identify by very large heart-shaped leaves (woolly underneath), purple thistle-like flowers, and hooked burs.",
                "Harvest first-year roots (rosette stage, no flower stalk) in fall or early spring.",
                "Peel and slice root; soak in water to prevent browning.",
                "Cook by boiling, stir-frying, or roasting. Young leaf stalks also edible peeled and cooked."],
         warnings=["First-year burdock rosette can resemble rhubarb or cocklebur — check for woolly leaf undersides.","Do not confuse with toxic nightshades in early growth."],
         related_entries=["l2-plants-cattail","l2-plants-jerusalem-artichoke","l2-plants-dandelion"],
         sources=["peterson-field-guides-edible-wild-plants","usda-plants-database"], confidence="high"),

    dict(id="l2-plants-jerusalem-artichoke", title="Jerusalem Artichoke / Sunchoke (Helianthus tuberosus)", subtopic="edible_plants",
         tags=["sunchoke","tuber","inulin","perennial"], region_relevance=["temperate","global"],
         summary="Perennial sunflower relative producing starchy tubers rich in inulin. Extremely productive and spreads aggressively. Good survival crop.",
         steps=["Identify by tall sunflower-like plant (2-3m) with small yellow flowers and rough opposite leaves.",
                "Dig tubers after first frost (sweeter) through winter.",
                "Eat raw (crunchy, nutty) or cooked (roast, boil, sauté).",
                "Replant small tubers for next season — very low maintenance."],
         warnings=["High inulin content causes significant gas/bloating in many people — introduce gradually.","Can become invasive — plant with containment plan."],
         related_entries=["l2-plants-burdock","l2-plants-cattail","l4-agriculture-soil-basics"],
         sources=["peterson-field-guides-edible-wild-plants","usda-plants-database","extension-edible-plants"], confidence="high"),

    dict(id="l2-plants-rose-hips", title="Rose Hips (Rosa spp.)", subtopic="edible_plants",
         tags=["rose-hips","vitamin-c","fall","winter","tea"], region_relevance=["global","temperate"],
         summary="Fruit of wild roses; extremely high in vitamin C (up to 50x more than oranges). Available fall through winter. Excellent dried for tea or processed into jam.",
         steps=["Identify by thorny stems, compound leaves with serrated leaflets, and red/orange fruit (hip) after flowering.",
                "Harvest after first frost for best sweetness.",
                "Split hips, remove seeds and irritating hairs inside.",
                "Dry for tea, or cook into syrup/jam.",
                "Avoid boiling — heat degrades vitamin C. Use warm water for tea."],
         warnings=["Interior hairs are an irritant — strain well and remove seeds.","Do not harvest from ornamental roses that may be sprayed."],
         related_entries=["l2-plants-pine-needle-tea","l2-plants-elderberry","l2-nutrition-deficiency-signs"],
         sources=["peterson-field-guides-edible-wild-plants","usda-plants-database"], confidence="high"),

    dict(id="l2-plants-elderberry", title="Elderberry (Sambucus nigra / canadensis)", subtopic="edible_plants",
         tags=["elderberry","berries","cooking-required","immune"], region_relevance=["temperate","global"],
         summary="Shrub/small tree producing clusters of small dark berries. Berries MUST be cooked — raw berries, leaves, bark, and stems contain cyanogenic glycosides.",
         steps=["Identify by compound leaves with 5-7 serrated leaflets, flat-topped white flower clusters, and dark purple-black berry clusters.",
                "Harvest fully ripe dark berries only.",
                "Cook berries before eating — boil into syrup, jam, or wine.",
                "Flowers can be used raw for tea or fritters (elderflower)."],
         warnings=["RAW berries cause nausea, vomiting, diarrhea.","Leaves, bark, stems, roots, and unripe berries are TOXIC.","Water elderberry (Sambucus racemosa — red berries) is more toxic.","Pokeweed berry clusters look similar — check leaf shape (simple vs compound)."],
         related_entries=["l2-plants-rose-hips","l2-plants-identification-protocol","l2-nutrition-deficiency-signs"],
         sources=["peterson-field-guides-edible-wild-plants","usda-plants-database","extension-edible-plants"], confidence="high"),

    dict(id="l2-plants-watercress", title="Watercress (Nasturtium officinale)", subtopic="edible_plants",
         tags=["watercress","stream","peppery","parasite-risk"], region_relevance=["global","temperate"],
         summary="Peppery aquatic green found in clean streams and springs. Highly nutritious but carries liver fluke risk if eaten raw from contaminated water.",
         steps=["Identify by compound leaves with rounded leaflets, hollow stems, small white four-petaled flowers, growing in flowing water.",
                "Harvest from clean, flowing water sources above any livestock grazing.",
                "Cook to eliminate liver fluke (Fasciola) risk if source is uncertain.",
                "Excellent in soups, stir-fries, or blanched."],
         warnings=["LIVER FLUKE RISK from contaminated water — cook if water source has livestock upstream.","Fool's watercress (Apium nodiflorum) is similar but also edible. Hemlock water dropwort is DEADLY — confirm hollow stem and leaf shape carefully."],
         related_entries=["l2-plants-cattail","l2-plants-stinging-nettle","l1-waterborne-illness-basics"],
         sources=["peterson-field-guides-edible-wild-plants","usda-plants-database"], confidence="high"),

    dict(id="l2-plants-wild-asparagus", title="Wild Asparagus (Asparagus officinalis)", subtopic="edible_plants",
         tags=["asparagus","spring","feral","roadsides"], region_relevance=["temperate"],
         summary="Feral asparagus grows along roadsides, fencerows, and irrigation ditches in temperate regions. Identical to cultivated asparagus. Spring spears are the edible part.",
         steps=["Find mature fern-like plants in fall/winter to mark locations for spring harvest.",
                "Return in spring to harvest emerging spears at 15-25cm height.",
                "Snap spears at natural breaking point.",
                "Eat raw or cooked — same as store-bought asparagus."],
         warnings=["Asparagus berries are mildly toxic — do not eat the red berries.","Avoid roadside plants exposed to heavy traffic or spraying."],
         related_entries=["l2-plants-cattail","l2-plants-burdock","l2-plants-seasonality"],
         sources=["peterson-field-guides-edible-wild-plants","usda-plants-database"], confidence="high"),

    dict(id="l2-plants-kudzu", title="Kudzu (Pueraria montana)", subtopic="edible_plants",
         tags=["kudzu","invasive","starch","vine"], region_relevance=["temperate","tropical"],
         summary="Aggressively invasive vine in southeastern US and warm climates. Leaves, flowers, shoots, and roots are all edible. Root starch is a traditional thickener in East Asian cooking.",
         steps=["Identify by large trifoliate leaves, purple fragrant flower clusters, and aggressive climbing growth.",
                "Young leaves and shoots: cook like greens.",
                "Flowers: eat raw, make tea or jelly.",
                "Roots: dig large tuberous roots, process for starch by crushing and washing.",
                "Root starch settles out of water — dry for flour."],
         warnings=["Avoid plants sprayed with herbicide — kudzu is heavily targeted.","Roots require significant effort to dig."],
         related_entries=["l2-plants-cattail","l2-plants-amaranth","l2-plants-jerusalem-artichoke"],
         sources=["peterson-field-guides-edible-wild-plants","usda-plants-database","extension-edible-plants"], confidence="high"),

    # ── MUSHROOMS ──
    dict(id="l2-mushrooms-chanterelle", title="Chanterelle (Cantharellus cibarius)", subtopic="mushrooms",
         tags=["chanterelle","golden","mycorrhizal","summer-fall"], region_relevance=["temperate","boreal"],
         summary="Prized golden funnel-shaped mushroom with false gills (ridges). Fruity apricot aroma. Mycorrhizal — found near hardwoods and conifers in summer/fall.",
         steps=["Identify by golden-orange color, vase/funnel shape, false gills (blunt forked ridges, not blade-like), white interior flesh.",
                "Spore print: pale yellow to white.",
                "Found on forest floor near oaks, beech, conifers. Never on wood.",
                "Cook thoroughly — do not eat raw. Excellent sautéed."],
         warnings=["LOOKALIKE: Jack-o-lantern (Omphalotus olearius) — grows in clusters ON wood, has true blade gills, and glows faintly green. Causes severe GI distress.","False chanterelle (Hygrophoropsis) has true gills and orange-brown color."],
         related_entries=["l2-mushrooms-safety","l2-mushrooms-deadly-lookalikes","l2-mushrooms-hen-of-the-woods"],
         sources=["nama-mushroom-id","extension-mushroom-guides"], confidence="high"),

    dict(id="l2-mushrooms-chicken-of-the-woods", title="Chicken of the Woods (Laetiporus sulphureus)", subtopic="mushrooms",
         tags=["chicken-of-the-woods","bracket","summer-fall"], region_relevance=["temperate","global"],
         summary="Large bright orange-and-yellow bracket fungus growing on hardwood trees. Meaty texture when young. One of the easier mushrooms to identify safely.",
         steps=["Identify by large overlapping shelves, bright orange top and yellow pore surface (no gills), growing on standing/fallen hardwood.",
                "Harvest young tender edges only — older portions become tough and chalky.",
                "Spore print: white.",
                "Cook thoroughly — slice and sauté, bread and fry, or add to soups."],
         warnings=["Some people have GI reactions — try a small amount first.","Avoid specimens growing on conifers, eucalyptus, or locust — higher reaction rates.","Do not eat raw."],
         related_entries=["l2-mushrooms-hen-of-the-woods","l2-mushrooms-safety","l2-mushrooms-oyster"],
         sources=["nama-mushroom-id","extension-mushroom-guides"], confidence="high"),

    dict(id="l2-mushrooms-morel", title="Morel (Morchella spp.)", subtopic="mushrooms",
         tags=["morel","spring","honeycomb","hollow"], region_relevance=["temperate","boreal"],
         summary="Highly prized spring mushroom with distinctive honeycomb-ridged cap. Key identification: cap is hollow from top to bottom when sliced lengthwise.",
         steps=["Identify by honeycomb/ridged cap attached at base of cap to stem, and completely hollow interior.",
                "Slice lengthwise to confirm single continuous hollow chamber.",
                "Found in spring near dead elms, tulip poplars, old orchards, and burn sites.",
                "Cook thoroughly before eating — never eat raw morels."],
         warnings=["FALSE MOREL (Gyromitra) is DEADLY — has brain-like wrinkled (not honeycomb) cap and is NOT hollow inside (cottony/chambered).","Always slice to confirm hollow interior.","Raw morels cause GI illness."],
         related_entries=["l2-mushrooms-safety","l2-mushrooms-deadly-lookalikes","l2-mushrooms-chanterelle"],
         sources=["nama-mushroom-id","extension-mushroom-guides"], confidence="high"),

    dict(id="l2-mushrooms-puffball", title="Giant Puffball (Calvatia gigantea)", subtopic="mushrooms",
         tags=["puffball","beginner","fall"], region_relevance=["temperate","global"],
         summary="Large white ball-shaped mushroom found in fields and meadows. Safe when interior is uniformly white. One of the safest beginner mushrooms with a critical safety check.",
         steps=["Identify by large (10-50cm+) round white form with no visible stem, cap, or gills externally.",
                "CRITICAL: Slice in half from top to bottom.",
                "Interior MUST be uniformly pure white with no outline of a developing mushroom inside.",
                "If uniformly white: safe to eat. Slice and cook like tofu — fry, bread, or grill."],
         warnings=["If interior shows ANY discoloration (yellow/brown/green): too old, discard.","If interior shows outline of cap/gills: it is a young Amanita (potentially deadly) — DISCARD IMMEDIATELY.","Always slice and inspect interior before eating."],
         related_entries=["l2-mushrooms-safety","l2-mushrooms-deadly-lookalikes","l2-mushrooms-chicken-of-the-woods"],
         sources=["nama-mushroom-id","extension-mushroom-guides"], confidence="high"),

    dict(id="l2-mushrooms-oyster", title="Oyster Mushroom (Pleurotus ostreatus)", subtopic="mushrooms",
         tags=["oyster","wood-decay","year-round","cultivatable"], region_relevance=["global","temperate"],
         summary="Common wood-decay mushroom growing in shelf-like clusters on dead/dying hardwoods. Mild flavor, good texture. Can fruit year-round in mild climates. Also easy to cultivate.",
         steps=["Identify by fan/oyster-shaped caps, white to gray-brown color, decurrent gills running down a short offset stem, growing on wood.",
                "Spore print: white to pale lilac.",
                "Harvest by twisting or cutting cluster from wood.",
                "Cook before eating — good sautéed, in soups, or dried."],
         warnings=["Angel wing (Pleurocybella porrigens) is a thin white lookalike on conifers — avoid white species on conifer wood.","Some people sensitive — try small amounts first."],
         related_entries=["l2-mushrooms-chicken-of-the-woods","l2-mushrooms-lions-mane","l4-agriculture-mushroom-cultivation"],
         sources=["nama-mushroom-id","extension-mushroom-guides"], confidence="high"),

    dict(id="l2-mushrooms-lions-mane", title="Lion's Mane (Hericium erinaceus)", subtopic="mushrooms",
         tags=["lions-mane","teeth","hardwood","medicinal"], region_relevance=["temperate","boreal"],
         summary="Distinctive white globe of cascading teeth/spines growing on dead or dying hardwoods. No dangerous lookalikes among Hericium species — all are edible.",
         steps=["Identify by white globe shape with long dangling spines/teeth (no cap, no gills).",
                "Found on dead or wounded hardwoods (oak, beech, maple), often high up.",
                "Harvest when white and firm — yellowing indicates age.",
                "Tear into pieces and sauté in butter — has a seafood/lobster-like flavor."],
         warnings=["All Hericium species are edible, making this a very safe genus.","Old specimens (yellow/brown) may cause GI upset — harvest fresh."],
         related_entries=["l2-mushrooms-oyster","l2-mushrooms-hen-of-the-woods","l2-mushrooms-safety"],
         sources=["nama-mushroom-id","extension-mushroom-guides"], confidence="high"),

    dict(id="l2-mushrooms-hen-of-the-woods", title="Hen of the Woods / Maitake (Grifola frondosa)", subtopic="mushrooms",
         tags=["maitake","hen-of-the-woods","fall","oak"], region_relevance=["temperate"],
         summary="Large polypore fruiting at the base of oaks in fall. Overlapping gray-brown fan-shaped caps. Excellent flavor and can produce massive fruitings (5-25kg).",
         steps=["Identify by cluster of overlapping gray-brown fan-shaped caps with white pore surface underneath, growing at base of living/dead oaks.",
                "Spore print: white.",
                "Harvest with knife; can return to same tree annually.",
                "Clean well (harbors debris). Cook thoroughly — roast, sauté, or dry."],
         warnings=["Berkeley's polypore (Bondarzewia berkeleyi) is a larger, tougher lookalike — has thicker flesh and bitter taste.","Black-staining polypore (Meripilus sumstinei) bruises black.","Both lookalikes are not deadly but are poor eating."],
         related_entries=["l2-mushrooms-chicken-of-the-woods","l2-mushrooms-chanterelle","l2-mushrooms-safety"],
         sources=["nama-mushroom-id","extension-mushroom-guides"], confidence="high"),

    dict(id="l2-mushrooms-deadly-lookalikes", title="Deadly Mushroom Lookalikes Reference", subtopic="mushrooms",
         tags=["deadly","amanita","death-cap","destroying-angel","false-morel","toxicology"], region_relevance=["global"],
         summary="Critical reference for the most dangerous mushroom species that mimic edible ones. Know these BEFORE foraging. When in doubt, throw it out.",
         steps=["DEATH CAP (Amanita phalloides): Greenish-yellow cap, white gills, skirt ring on stem, bulbous volva at base. Often mistaken for paddy straw mushroom. Fatal liver/kidney failure in 6-12 hours.",
                "DESTROYING ANGEL (Amanita bisporigera/virosa): Pure white, elegant. White gills, ring, and volva. Can be mistaken for button mushroom, puffball (when young), or field mushroom.",
                "FALSE MOREL (Gyromitra esculenta): Brain-like wrinkled cap (not honeycomb). Interior is NOT hollow — has chambers/cottony tissue. Contains gyromitrin (metabolizes to monomethylhydrazine).",
                "JACK-O-LANTERN (Omphalotus olearius): Orange, grows in clusters ON wood. True blade gills. Mimics chanterelle. Severe GI distress but rarely fatal.",
                "AUTUMN SKULLCAP (Galerina marginata): Small brown mushroom on wood with ring. Mimics honey mushroom. Contains same toxins as death cap."],
         warnings=["Amanita toxins have a delayed onset (6-24 hours) — victim may feel fine initially then develop fatal organ failure.","No folk test (silver spoon, garlic color, animal testing) is reliable.","When in doubt, ALWAYS discard.","Single death cap can kill an adult."],
         related_entries=["l2-mushrooms-safety","l2-mushrooms-morel","l2-mushrooms-chanterelle","l2-mushrooms-puffball"],
         sources=["nama-mushroom-id","extension-mushroom-guides","openstax-biology-2e"], confidence="high"),

    # ── FISHING & HUNTING ──
    dict(id="l2-fishing-improvised-methods", title="Improvised Fishing Methods", subtopic="fishing_hunting_knowledge",
         tags=["fishing","improvised","hook","trap","line"], region_relevance=["global"],
         summary="Methods for catching fish with minimal or improvised equipment — hooks from bone/thorns/wire, line from plant fiber or paracord, and passive trap designs.",
         steps=["Fashion hooks from safety pins, thorns, bone splinters, wire, or carved hardwood (gorge hooks).",
                "Use paracord inner strands, braided plant fibers, or dental floss as line.",
                "Bait with insects, worms, berries, or small meat scraps.",
                "Build passive traps: funnel traps from woven sticks in streams, trotlines across pools.",
                "Set lines at dawn/dusk for best results."],
         warnings=["Check local regulations where law still applies.","Improvised hooks are fragile — set multiple lines.","Avoid consuming fish from visibly polluted water."],
         related_entries=["l2-fishing-knots","l2-fish-identification-freshwater","l2-insect-foraging"],
         sources=["state-wildlife-hunter-ed","bsa-handbook"], confidence="high"),

    dict(id="l2-fishing-knots", title="Essential Fishing Knots", subtopic="fishing_hunting_knowledge",
         tags=["knots","fishing","line","hook"], region_relevance=["global"],
         summary="Core knots for attaching hooks, joining lines, and creating loops for fishing applications.",
         steps=["Improved clinch knot: primary hook-to-line attachment. 5 wraps through eye, back through loop.",
                "Palomar knot: strongest simple knot for hooks/swivels. Double line through eye, overhand knot, pass hook through loop.",
                "Surgeon's knot: join two lines of different diameter. Overlap ends, double overhand, pull tight.",
                "Loop knot: non-slip mono loop for lure movement. Overhand knot in line, pass through eye, wrap 5x, back through overhand."],
         warnings=["Wet knots before tightening to prevent heat damage to line.","Test every knot before use."],
         related_entries=["l2-fishing-improvised-methods","l1-shelter-knots-and-lashing","l2-fish-identification-freshwater"],
         sources=["state-wildlife-hunter-ed","bsa-handbook"], confidence="high"),

    dict(id="l2-trapping-small-game", title="Passive Small Game Trapping Principles", subtopic="fishing_hunting_knowledge",
         tags=["trapping","snare","deadfall","small-game"], region_relevance=["global"],
         summary="Passive trapping methods that work while you do other tasks. Focuses on principles of funnel, trigger, and restraint mechanisms.",
         steps=["Identify game trails, runs, and feeding areas through tracks and sign.",
                "Simple snare: running noose of wire/cord at head height of target animal on a known trail.",
                "Deadfall: figure-4 trigger with weighted rock/log over bait platform.",
                "Funnel trap: guide fences narrowing to a box or enclosure.",
                "Set multiple traps (10+) — success rate per trap is low. Check twice daily."],
         warnings=["Trapping may be illegal where law enforcement exists.","Check traps frequently to prevent suffering.","Disease risk from handling wild animals — use gloves."],
         related_entries=["l2-tracking-basics","l2-field-dressing-overview","l2-fishing-improvised-methods"],
         sources=["state-wildlife-hunter-ed","bsa-handbook"], confidence="high"),

    dict(id="l2-insect-foraging", title="Edible Insect Identification and Preparation", subtopic="fishing_hunting_knowledge",
         tags=["insects","protein","foraging","entomophagy"], region_relevance=["global"],
         summary="Insects are the most abundant and accessible animal protein source. Crickets, grasshoppers, grubs, and ants are widely eaten worldwide. Key rule: cook all insects before eating.",
         steps=["Crickets and grasshoppers: collect in early morning when cold/sluggish. Remove legs (spiny). Roast or fry.",
                "Grubs (beetle larvae): found in rotting logs. White, C-shaped. Roast until crispy.",
                "Ants: collect workers (avoid fire ants). Roast to neutralize formic acid.",
                "Termites: high in fat and protein. Collect from mounds. Roast.",
                "General rule: avoid brightly colored insects (warning coloration), hairy caterpillars, and strong-smelling bugs."],
         warnings=["ALWAYS cook insects — raw insects may carry parasites.","Avoid brightly colored, hairy, or pungent species.","People with shellfish allergies may react to insects (similar chitin proteins)."],
         related_entries=["l2-nutrition-macros-basics","l2-fishing-improvised-methods","l2-nutrition-caloric-needs"],
         sources=["state-wildlife-hunter-ed","openstax-biology-2e","extension-edible-plants"], confidence="high"),

    dict(id="l2-shellfish-foraging", title="Coastal Shellfish Safety and Foraging", subtopic="fishing_hunting_knowledge",
         tags=["shellfish","coastal","mussels","clams","toxin-risk"], region_relevance=["marine","temperate","tropical"],
         summary="Coastal shellfish (mussels, clams, oysters, limpets) are calorie-dense and require no tools to collect, but carry serious toxin and contamination risks.",
         steps=["Collect from rocks and tidal flats at low tide.",
                "Mussels: pull from rocks, discard any that don't close when tapped (dead).",
                "Clams: dig in sand/mud at water line.",
                "Cook all shellfish thoroughly — boil until shells open.",
                "Discard any that do not open after cooking."],
         warnings=["RED TIDE / paralytic shellfish poisoning (PSP) is not destroyed by cooking — can be fatal.","Avoid harvesting during warm months or algal blooms.","Do not eat shellfish near sewage outflows, ports, or industrial areas.","Quarantine areas may not be marked post-collapse."],
         related_entries=["l2-fish-identification-freshwater","l2-nutrition-food-safety-field","l1-water-contamination-risk"],
         sources=["state-wildlife-hunter-ed","cdc-water-emergency"], confidence="medium"),

    dict(id="l2-fish-identification-freshwater", title="Common Edible Freshwater Fish", subtopic="fishing_hunting_knowledge",
         tags=["fish","freshwater","identification","protein"], region_relevance=["global","temperate"],
         summary="Basic identification of common edible freshwater fish families. Most freshwater fish are edible when properly cooked, but some carry parasite risks.",
         steps=["Sunfish/bluegill: small, pan-sized, found in ponds and slow streams. Easiest beginner target.",
                "Catfish: bottom feeders, whisker barbels, scaleless. Found in rivers and ponds. Excellent eating.",
                "Trout: cold clear streams, spotted sides. Cook same day — spoils fast.",
                "Carp: large, common in warm water. Bony but edible — score flesh before cooking.",
                "General: gut and cook all fish promptly. Firm flesh and clear eyes indicate freshness."],
         warnings=["Cook all freshwater fish thoroughly — many carry parasites (tapeworm, liver flukes).","Avoid fish from obviously polluted water.","Pufferfish (if encountered) are extremely toxic — avoid entirely."],
         related_entries=["l2-fishing-improvised-methods","l2-fishing-knots","l2-nutrition-food-safety-field"],
         sources=["state-wildlife-hunter-ed","openstax-biology-2e"], confidence="high"),

    dict(id="l2-game-bird-basics", title="Game Bird Field Knowledge", subtopic="fishing_hunting_knowledge",
         tags=["birds","upland","waterfowl","hunting"], region_relevance=["global","temperate"],
         summary="Basic knowledge of common game birds, their habits, and field preparation. Upland birds (grouse, pheasant, quail) and waterfowl (ducks, geese) are widespread protein sources.",
         steps=["Learn flight patterns and habitat preferences by species.",
                "Upland birds: found in edge habitat (field/forest borders). Flush from cover.",
                "Waterfowl: found on water bodies. Most active dawn/dusk during migration.",
                "Field dress promptly: pluck or skin, remove crop and entrails.",
                "Cook thoroughly — wild birds may carry avian parasites."],
         warnings=["Raptor and songbird hunting is widely prohibited and ecologically harmful.","Avian influenza risk — avoid visibly sick birds.","Always cook wild fowl well-done."],
         related_entries=["l2-tracking-basics","l2-field-dressing-overview","l2-animal-behavior-seasons"],
         sources=["state-wildlife-hunter-ed","openstax-biology-2e"], confidence="high"),

    dict(id="l2-animal-behavior-seasons", title="Animal Seasonal Behavior and Migration Patterns", subtopic="fishing_hunting_knowledge",
         tags=["migration","breeding","seasons","ecology","behavior"], region_relevance=["global"],
         summary="Understanding seasonal animal behavior cycles improves foraging success and safety. Animals are most active and predictable during feeding, breeding, and migration periods.",
         steps=["Spring: breeding season — males territorial and visible. Nesting birds aggressive. Fish spawning in shallows.",
                "Summer: dispersed feeding. Dawn/dusk activity peaks. Water sources become gathering points.",
                "Fall: migration and fat-building. Best hunting season — animals are heaviest. Salmon runs. Nut/fruit competition.",
                "Winter: reduced activity, concentrated near food/shelter. Tracking easiest in snow. Hibernators unavailable."],
         warnings=["Breeding animals (especially bears, moose, elk) are more aggressive.","Avoid disturbing nesting sites.","Predator activity increases near concentrated prey."],
         related_entries=["l2-tracking-basics","l2-game-bird-basics","l2-plants-seasonality"],
         sources=["state-wildlife-hunter-ed","openstax-biology-2e"], confidence="high"),

    # ── NUTRITION ──
    dict(id="l2-nutrition-macros-basics", title="Macronutrient Requirements Under Survival Conditions", subtopic="nutrition",
         tags=["nutrition","protein","fat","carbs","calories"], region_relevance=["global"],
         summary="Minimum macronutrient needs shift under survival stress. Caloric needs increase with cold, exertion, and injury. Fat is the most calorie-dense macronutrient and critical for long-term survival.",
         steps=["Baseline adult needs: ~2000-2500 kcal/day sedentary; 3000-4500+ under heavy exertion or cold.",
                "Protein: 0.8-1.2g/kg body weight minimum. Critical for wound healing and muscle maintenance.",
                "Fat: 9 kcal/g (vs 4 for protein/carbs). Prioritize fat sources for caloric efficiency.",
                "Carbohydrates: primary quick energy. Grains, tubers, fruits, honey.",
                "Prioritize calories over nutritional balance in acute survival — starvation kills faster than deficiency."],
         warnings=["Protein-only diet without fat/carbs causes 'rabbit starvation' — potentially fatal.","Caloric deficit compounds rapidly under cold exposure.","Dehydration mimics hunger — hydrate first."],
         related_entries=["l2-nutrition-caloric-needs","l2-nutrition-deficiency-signs","l2-plants-amaranth"],
         sources=["who-basic-emergency-care-2018","openstax-biology-2e","red-cross-first-aid-cpr-aed"], confidence="high"),

    dict(id="l2-nutrition-deficiency-signs", title="Recognizing Vitamin and Mineral Deficiencies", subtopic="nutrition",
         tags=["deficiency","vitamins","minerals","scurvy","diagnosis"], region_relevance=["global"],
         summary="Field recognition of common nutritional deficiencies that develop over weeks to months of restricted diet. Early detection enables targeted foraging.",
         steps=["Vitamin C (scurvy): bleeding gums, loose teeth, slow wound healing, fatigue. Onset 1-3 months. Sources: rose hips, pine needles, greens, berries.",
                "Vitamin A: night blindness, dry skin. Sources: orange/yellow plants, liver, dark greens.",
                "Iron: fatigue, pallor, weakness, rapid heartbeat. Sources: nettle, meat, dark greens.",
                "B vitamins: cracked lips, confusion, dermatitis. Sources: whole grains, meat, legumes.",
                "Iodine: goiter (neck swelling), fatigue. Sources: seaweed, fish, iodized salt."],
         warnings=["Scurvy can become fatal if untreated.","Night blindness from vitamin A deficiency impairs safety.","Iron deficiency severely reduces work capacity."],
         related_entries=["l2-nutrition-macros-basics","l2-plants-rose-hips","l2-plants-pine-needle-tea","l2-plants-stinging-nettle"],
         sources=["who-basic-emergency-care-2018","openstax-biology-2e"], confidence="high"),

    dict(id="l2-nutrition-caloric-needs", title="Caloric Budgeting Under Exertion", subtopic="nutrition",
         tags=["calories","energy-balance","exertion","planning"], region_relevance=["global"],
         summary="Systematic approach to estimating caloric expenditure vs intake to prevent dangerous energy debt. Critical for rationing and work planning.",
         steps=["Estimate basal metabolic rate: ~1500-1800 kcal/day for average adult at rest.",
                "Add activity multiplier: light work 1.5x, moderate 2x, heavy labor/cold 2.5-3x.",
                "Track food intake roughly by source category.",
                "If intake < expenditure: reduce non-essential activity, increase foraging priority.",
                "Plan rest days into work schedules to reduce total caloric need."],
         warnings=["Sustained caloric deficit causes muscle wasting, impaired judgment, and immune suppression.","Cold environments dramatically increase caloric needs.","Children and pregnant/nursing women need proportionally more."],
         related_entries=["l2-nutrition-macros-basics","l2-nutrition-deficiency-signs","l2-nutrition-food-safety-field"],
         sources=["who-basic-emergency-care-2018","openstax-biology-2e"], confidence="high"),

    dict(id="l2-nutrition-food-safety-field", title="Preventing Foodborne Illness in Field Conditions", subtopic="nutrition",
         tags=["food-safety","contamination","cooking","storage"], region_relevance=["global"],
         summary="Field food safety principles to prevent the GI illness that can be deadly when medical care is unavailable. Cook thoroughly, eat promptly, store carefully.",
         steps=["Cook all meat, fish, and eggs to internal temps that kill pathogens (boiling/thorough cooking if no thermometer).",
                "Eat cooked food within 2 hours or keep below 5°C / above 60°C.",
                "Clean hands and tools before food preparation.",
                "Separate raw meat from other foods.",
                "When in doubt about freshness: smell, visual check, discard if any doubt."],
         warnings=["Diarrheal illness causes rapid dehydration — potentially fatal without treatment.","Botulism risk in improperly preserved/canned foods.","Do not rely on smell alone for meat safety."],
         related_entries=["l2-meat-preservation","l2-nutrition-macros-basics","l1-medical-dehydration"],
         sources=["usda-meat-preservation","who-basic-emergency-care-2018","cdc-water-emergency"], confidence="high"),
]

def main():
    ENTRIES.mkdir(parents=True, exist_ok=True)
    for entry in SEEDS:
        meta = {
            "id": entry["id"],
            "title": entry["title"],
            "category": "L2_food_biology",
            "subtopic": entry["subtopic"],
            "tags": entry["tags"],
            "region_relevance": entry["region_relevance"],
            "summary": entry["summary"],
            "steps": entry["steps"],
            "warnings": entry["warnings"],
            "related_entries": entry["related_entries"],
            "sources": entry["sources"],
            "last_verified": TODAY,
            "confidence": entry["confidence"],
            "offline_assets": [],
        }
        front = yaml.safe_dump(meta, sort_keys=False).strip()
        body = "---\n" + front + "\n---\n\n## Overview\n" + entry["summary"] + "\n\n## Step-by-step\n"
        body += "\n".join(f"{i+1}. {s}" for i, s in enumerate(entry["steps"]))
        body += "\n\n## Warnings\n" + "\n".join(f"- {w}" for w in entry["warnings"]) + "\n"

        out = ENTRIES / f"{entry['id']}.md"
        out.write_text(body, encoding="utf-8")

    print(f"Wrote {len(SEEDS)} L2 entries.")

if __name__ == "__main__":
    main()
