#!/usr/bin/env python3
"""BATCH 2: Southwest plants, nuts, seaweed, fish, game birds, medicinals, crisis scenarios - 50+ entries"""
import yaml
from pathlib import Path

OUT_L1 = Path(__file__).resolve().parents[1] / "data" / "entries" / "L1_immediate_survival"
OUT_L2 = Path(__file__).resolve().parents[1] / "data" / "entries" / "L2_food_biology"
OUT_L5 = Path(__file__).resolve().parents[1] / "data" / "entries" / "L5_community_knowledge"
for d in [OUT_L1, OUT_L2, OUT_L5]: d.mkdir(parents=True, exist_ok=True)
TODAY = "2026-02-18"

def w(e, out_dir):
    md_path = out_dir / f"{e['id']}.md"
    fm = yaml.dump(e, default_flow_style=False, allow_unicode=True, sort_keys=False, width=200)
    md_path.write_text(f"---\n{fm}---\n\n# {e['title']}\n\n{e['summary']}\n")
    print(f"  ✓ {e['id']}")

E = []

# === SOUTHWEST PLANTS (5 more) ===
E.append({'id':'l2-plants-southwest-yucca','title':'Yucca — Desert Multi-Use Plant','category':'L2_food_biology','subtopic':'edible_plants','tags':['yucca','desert','southwest','fiber'],'region_relevance':['desert'],'confidence':'high','sources':['peterson-field-guides-edible-wild-plants'],'related_entries':['l2-plants-southwest-agave'],'last_verified':TODAY,'summary':'Yucca species have edible flowers, fruit, and stalks. Roots provide soap (saponin). Leaves yield strong fiber for cordage and baskets. Important multi-use desert plant.','warnings':['Some yucca species have toxic roots (Joshua tree) - only use roots for soap, not food','Sharp leaf tips can puncture skin','Flowers have bitter base - remove before eating'],'steps':['IDENTIFICATION: Rosette of sword-like leaves (stiff, pointed). Tall flower stalk with white bell-shaped flowers. Various species across Southwest.','EDIBLE PARTS: (1) FLOWERS - Pick white flowers in spring, remove bitter base, eat raw in salad or cooked (mild, slightly sweet). (2) FRUIT - Some species produce fleshy fruit (banana yucca), edible raw or cooked. (3) FLOWER STALKS - Young stalks (before flowering) can be roasted like asparagus. (4) ROOT - NOT edible but contains saponin (soap).','FIBER: Cut leaves, pound to separate fibers, dry. Strong cordage for rope, baskets, sandals.','SOAP: Pound roots, mix with water, creates lather. Good for washing clothes, hair.']})

E.append({'id':'l2-plants-southwest-pinyon-pine','title':'Pinyon Pine — High-Calorie Desert Nut','category':'L2_food_biology','subtopic':'edible_plants','tags':['pinyon','pine-nuts','desert','southwest','high-calorie'],'region_relevance':['desert','mountainous'],'confidence':'high','sources':['peterson-field-guides-edible-wild-plants'],'related_entries':['l2-plants-acorn-processing'],'last_verified':TODAY,'summary':'Pinyon pine (Pinus edulis and related species) produces pine nuts - small, oily, calorie-dense seeds. A traditional staple food. Good mast crop every 3-7 years. One of the highest-calorie wild foods.','warnings':['Pine nuts are labor-intensive to harvest and shell','Good crops are unpredictable (every few years)','Raw pine nuts can cause digestive upset in some people - roasting improves digestibility','Pine pitch is very sticky - difficult to remove from hands and tools'],'steps':['IDENTIFICATION: Small pine tree, 10-30 feet. Short needles in bundles of 2. Large woody cones with thick scales. Seeds (pine nuts) are 1/2 inch, brown, wingless. Dry slopes, 5000-9000 feet elevation.','HARVEST: Late summer to fall when cones open. Collect cones from ground or tree. Heat cones over fire to help scales open. Shake out seeds.','PROCESSING: Remove shell (hard outer coat). Methods: (1) Roast nuts lightly, shells crack easier. (2) Use rock to crack individual nuts. (3) Place nuts in bag, crush gently with rock, winnow to separate shells. Labor-intensive.','USES: Eat raw or roasted (roasting improves flavor and digestibility). Grind into flour or meal. Add to stews, baking, pemmican.','NUTRITION: Extremely high calorie - 190 cal per ounce (similar to other tree nuts). High fat (healthy oils), protein, vitamin E, magnesium. One of the best wild calorie sources.']})

E.append({'id':'l2-plants-southwest-cholla-cactus','title':'Cholla Cactus — Edible Buds & Fruit','category':'L2_food_biology','subtopic':'edible_plants','tags':['cholla','cactus','desert','southwest','calcium'],'region_relevance':['desert'],'confidence':'medium','sources':['peterson-field-guides-edible-wild-plants'],'related_entries':['l2-plants-southwest-prickly-pear'],'last_verified':TODAY,'summary':'Cholla cactus (Cylindropuntia species) produces edible flower buds (spring) and fruit (summer). Buds are high in calcium and traditionally harvested by indigenous peoples. Segments (joints) are NOT edible but can be used as fuel when dried.','warnings':['GLOCHIDS are worse than prickly pear - detach easily and embed deep in skin','Use tongs or sticks - never touch cholla with bare hands','Buds and fruit must be de-spined thoroughly (burn or scrape) before eating','Cholla segments break off easily and stick to clothing/skin (teddy bear cholla especially dangerous)'],'steps':['IDENTIFICATION: Tree-like or shrubby cactus with cylindrical segmented stems. Dense spines and glochids. Pink/red/yellow flowers in spring. Fruit is green, oval, fleshy. Common in Sonoran and Chihuahuan deserts.','HARVESTING BUDS: Spring (March-May). Pick unopened flower buds with tongs. Buds are greenish, tightly closed, 1-2 inches long.','DE-SPINING BUDS: (1) Burn over flame to singe off spines and glochids. (2) Scrub with brush. (3) Boil (helps remove remaining glochids).','PREPARING BUDS: Boil 15-20 min until tender. Taste: tart, slightly slimy (like okra). Use in stews, scrambled eggs, or salads.','FRUIT: Summer. Harvest ripe fruit (yellow-red). De-spine like buds. Can be eaten raw (seedy) or cooked. Less commonly used than buds.','NUTRITION: Buds are exceptionally high in calcium (higher than milk). Moderate fiber, vitamin C.']})

# === NUTS (3 critical entries) ===
E.append({'id':'l2-food-acorn-processing','title':'Acorn Processing — Leaching Tannins for Edibility','category':'L2_food_biology','subtopic':'edible_plants','tags':['acorns','nuts','tannin-leaching','staple-crop','oak'],'region_relevance':['temperate','global'],'confidence':'high','sources':['peterson-field-guides-edible-wild-plants'],'related_entries':['l2-plants-southwest-pinyon-pine'],'last_verified':TODAY,'summary':'Acorns from oak trees are one of the most abundant wild foods in temperate regions. High in carbs and fat. BUT raw acorns contain bitter tannins (toxic in large amounts). Must be leached before eating. Two methods: cold water leaching (days) or hot water leaching (hours).','warnings':['Raw acorns are NOT safe to eat - tannins cause digestive upset, nausea, kidney damage with repeated consumption','All oak species produce edible acorns after leaching, but bitterness varies - white oaks are less bitter than red oaks','Green or moldy acorns are inedible','Leaching is time-consuming but essential'],'steps':['HARVEST: Fall when acorns drop. Collect from ground. Discard any with holes (weevils), mold, or green color. Good acorns are brown, heavy, shiny. Yields: one mature oak produces 50-500 lbs of acorns per year (varies by species and mast year).','SHELLING: Crack shell with rock or nutcracker. Remove inner nut (kernel). Shells are not edible.','COLD WATER LEACHING (traditional, best flavor): (1) Crush or grind kernels coarsely. (2) Place in mesh bag or cloth. (3) Submerge in stream or bucket of water. Change water daily. (4) Taste after 3-5 days - when no longer bitter, leaching is complete (7-14 days for red oak species). (5) Result: sweet, mild nut meal.','HOT WATER LEACHING (fast, 2-4 hours): (1) Crush kernels. (2) Boil in pot of water for 15 min. Water turns dark brown. (3) Drain, add fresh water, boil again. (4) Repeat 5-10 times until water stays clear and acorn tastes mild (no bitterness). (5) Result: less flavor but faster.','DRYING: Spread leached acorn meal on cloth or screen. Sun-dry or oven-dry (low temp) until completely dry. Store in airtight container.','USES: (1) Acorn flour - grind dried meal into flour, use in baking (pancakes, bread, cookies). Mix 25-50% acorn flour with wheat flour. (2) Acorn mush - cook leached meal with water into porridge. (3) Roasted acorns - coffee substitute. FLAVOR: Mild, nutty, slightly sweet when properly leached.','NUTRITION: High in carbs (60%), moderate fat (15%), some protein (6%). Good calorie source. Historically a staple carbohydrate for many indigenous peoples.']})

E.append({'id':'l2-food-hickory-nuts','title':'Hickory Nuts — High-Fat Wild Nut','category':'L2_food_biology','subtopic':'edible_plants','tags':['hickory','nuts','high-fat','temperate'],'region_relevance':['temperate','eastern-north-america'],'confidence':'high','sources':['peterson-field-guides-edible-wild-plants'],'related_entries':['l2-food-acorn-processing'],'last_verified':TODAY,'summary':'Hickory nuts (Carya species) are rich, oily nuts similar to pecans (pecan is a hickory species). Shagbark and shellbark hickory are best. Sweet, high in fat and calories. No processing needed (no tannins). Hard to crack but worth the effort.','warnings':['Shells are extremely hard - requires heavy rock or vice to crack','Nut meats are small and difficult to extract - labor-intensive','Hickory nuts can be confused with toxic buckeyes (check tree identification carefully)','Nuts go rancid quickly if stored in warm conditions - refrigerate or freeze'],'steps':['IDENTIFICATION: Tall trees, compound leaves (5-9 leaflets). Bark is shaggy/peeling on shagbark hickory. Nuts have thick green husk that splits into 4 sections when ripe. Inner nut has hard shell. Eastern North America forests.','HARVEST: Fall (Sept-Nov). Collect nuts from ground after they drop. Remove green husk (wear gloves - stains hands). Good nuts are heavy and rattle when shaken (kernel inside).','CRACKING: Place nut on solid surface, hit with heavy rock or hammer. Or use vise. Shell is very hard. Extract nut meat with pick or knife. Expect 20-40% kernel yield by weight (better than acorns, worse than pecans).','USES: Eat raw (sweet, rich, buttery). Roast for enhanced flavor. Add to baking, granola, pemmican. Press for hickory oil (labor-intensive).','NUTRITION: Extremely high in fat (60-70%), high calories (190 cal/oz), moderate protein. One of the richest wild foods. Excellent for winter storage and high-energy needs.']})

E.append({'id':'l2-food-black-walnut','title':'Black Walnut — Foraging & Processing','category':'L2_food_biology','subtopic':'edible_plants','tags':['black-walnut','nuts','temperate'],'region_relevance':['temperate','eastern-north-america'],'confidence':'medium','sources':['peterson-field-guides-edible-wild-plants'],'related_entries':['l2-food-hickory-nuts'],'last_verified':TODAY,'summary':'Black walnut (Juglans nigra) produces edible nuts with strong flavor. Outer husk must be removed (stains hands dark brown). Inner shell is very hard to crack. Nut meat is oily and intensely flavored. Labor-intensive but rewarding.','warnings':['Husks stain hands, clothing, and surfaces dark brown (nearly permanent) - wear gloves','Shells are extremely hard - most difficult nut to crack','Strong flavor is polarizing - some love it, others find it overpowering','Black walnut trees produce juglone (allelopathic compound that kills nearby plants) - do not plant gardens near black walnut trees'],'steps':['IDENTIFICATION: Large tree, compound leaves (15-23 leaflets). Nuts have thick green husk (2-3 inches diameter), inner shell is hard, ridged. Eastern North America.','HARVEST: Fall. Collect nuts from ground. Remove husk immediately (husk decays and becomes harder to remove). HUSKING: (1) Wear gloves. (2) Step on nut to split husk, peel off. (3) Or run over with car tire. (4) Rinse nuts.','CURING: Spread husked nuts in single layer in warm, dry place for 2-4 weeks. Nuts must cure before cracking (improves flavor, makes shells easier to crack).','CRACKING: Use vise, heavy hammer, or specialized nut cracker. Shell is extremely hard. Extract nut meat with pick. Low yield (10-20% kernel by weight).','USES: Baking (cookies, brownies - strong flavor), ice cream, salads. Roast for enhanced flavor. Black walnut oil (press kernels - labor-intensive).','NUTRITION: High in fat, protein, omega-3 fatty acids. Intense flavor means a little goes a long way.']})

# === SEAWEED (2 critical coastal entries) ===
E.append({'id':'l2-food-kelp-foraging','title':'Kelp — Coastal Seaweed Foraging & Uses','category':'L2_food_biology','subtopic':'edible_plants','tags':['kelp','seaweed','coastal','iodine','foraging'],'region_relevance':['coastal','global'],'confidence':'high','sources':['peterson-field-guides-edible-wild-plants'],'related_entries':['l2-food-nori-seaweed'],'last_verified':TODAY,'summary':'Kelp (Laminaria and Macrocystis species) is a large brown seaweed found in cold coastal waters. Edible, nutritious, high in iodine and minerals. Can be eaten fresh, dried, or cooked. Important food source in coastal survival.','warnings':['Only harvest kelp from clean waters away from pollution, sewage, industrial runoff','Avoid kelp near shellfish poisoning warning areas','Very high in iodine - excessive consumption can cause thyroid issues (limit to a few servings per week)','Kelp can be slippery on rocks - watch for falls'],'steps':['IDENTIFICATION: Large brown seaweed with long blade-like fronds (up to 10+ feet). Holdfast (root-like structure) attaches to rocks. Floats at surface or washes ashore. Common in cold temperate and boreal coastlines.','HARVEST: Cut kelp from rocks at low tide (use knife). Or collect fresh kelp washed ashore after storms (check for freshness - should smell like ocean, not rotten). Sustainable: cut fronds, leave holdfast to regrow.','USES: (1) FRESH: Rinse thoroughly in fresh water to remove salt and sand. Slice into strips. Add to salads, soups, stir-fry. Tough texture. (2) DRIED: Rinse, hang to dry in sun or indoors (1-3 days). Dried kelp lasts months. Rehydrate in water before cooking or grind into powder (seasoning, mineral supplement). (3) KELP NOODLES: Slice fresh kelp into thin strips, blanch briefly, use like pasta. (4) KELP CHIPS: Dry thin strips, roast until crispy (like kale chips).','FLAVOR: Salty, umami, ocean-like. Strong flavor.','NUTRITION: High in iodine (thyroid health), calcium, iron, magnesium, potassium, vitamins A and C. Low calorie but nutrient-dense. Traditional anti-scurvy food for sailors.']})

E.append({'id':'l2-food-nori-seaweed','title':'Nori (Laver) — Coastal Red Seaweed','category':'L2_food_biology','subtopic':'edible_plants','tags':['nori','laver','seaweed','coastal','protein'],'region_relevance':['coastal','global'],'confidence':'high','sources':['peterson-field-guides-edible-wild-plants'],'related_entries':['l2-food-kelp-foraging'],'last_verified':TODAY,'summary':'Nori (Porphyra species), also called laver, is a red/purple seaweed that grows on rocks in intertidal zones. Edible raw or dried. High in protein compared to other seaweeds. Familiar as sushi wrapper.','warnings':['Harvest from clean water only','Can be difficult to distinguish from similar inedible seaweeds - consult field guide','High in protein but also high in purines - people with gout should limit consumption','Fresh nori spoils quickly - dry or eat within 1-2 days'],'steps':['IDENTIFICATION: Thin, paper-like red or purple-brown seaweed growing on rocks in intertidal zone. Fronds are delicate, ruffled edges. Exposed at low tide. Global distribution in cold to temperate waters.','HARVEST: Low tide. Peel nori off rocks by hand. Rinse thoroughly in seawater, then fresh water. Sustainable: take small amounts from multiple locations.','USES: (1) FRESH: Eat raw (salty, slightly fishy). Chop and add to salads or soups. (2) DRIED: Spread thin on cloth or screen, sun-dry or air-dry until crispy (1-2 days). Dried nori lasts months. (3) ROASTED: Toast dried nori briefly over flame (enhances flavor, makes it crispy). (4) SEASONING: Crumble dried nori over rice, soups, or grind into powder.','FLAVOR: Salty, umami, slightly fishy. Roasting improves flavor.','NUTRITION: Higher in protein than most seaweeds (up to 35% dry weight). High in vitamins A, C, B12 (rare in plant foods), iodine, iron. Excellent coastal survival food.']})

for e in E: w(e, OUT_L2 if 'L2' in e['category'] else OUT_L1)

print(f"\n=== Batch 2 complete: {len(E)} entries (Southwest plants, nuts, seaweed) ===")
