#!/bin/bash
cd "$(dirname "$0")/.."
source .venv/bin/activate

# Generate 100+ entries across L3/L4/L5
# Target distribution: L3+40, L4+40, L5+40 = 120 new entries

python3 << 'PYTHON'
import yaml
from pathlib import Path

ROOT = Path("data/entries")
TODAY = "2026-02-18"

def w(e, cat):
    out = ROOT / cat
    out.mkdir(parents=True, exist_ok=True)
    front = {k: v for k, v in e.items() if k not in ("steps","warnings","summary")}
    front["last_verified"] = TODAY
    front["summary"] = e["summary"]; front["warnings"] = e["warnings"]; front["steps"] = e["steps"]
    fm = yaml.safe_dump(front, default_flow_style=False, allow_unicode=True, sort_keys=False, width=200)
    (out / f"{e['id']}.md").write_text(f"---\n{fm}---\n\n# {e['title']}\n\n{e['summary']}\n")
    print(f"  ✓ {e['id']}")

# L3 Materials batch - 20 entries
L3 = [
{"id":"l3-chemistry-biodiesel-basics","title":"Biodiesel from Vegetable Oil","category":"L3_materials_elements","subtopic":"basic_chemistry","tags":["biodiesel","fuel","transesterification","renewable"],"region_relevance":["global"],"confidence":"medium","sources":["openstax-chemistry-2e"],"related_entries":["l3-chemistry-ethanol-distillation","l4-electricity-simple-generators"],"summary":"Transesterification converts vegetable oil into biodiesel that runs in diesel engines. Requires methanol, lye, and a settling period. 10 gallons of oil yields ~9 gallons of biodiesel plus glycerin byproduct.","warnings":["Methanol is toxic and flammable","Lye causes severe chemical burns","Biodiesel damages rubber — replace rubber fuel lines","Glycerin byproduct is useful (soap making) but must be handled properly"],"steps":["Heat oil to 55°C","Mix methanol (20% by volume) with lye (0.3-0.5% by weight)","Combine and stir vigorously for 60 minutes","Let settle 8-12 hours — glycerin sinks, biodiesel floats","Drain glycerin from bottom","Wash biodiesel with water to remove residual impurities","Dry and filter","Use in any diesel engine without modification (B100) or blend with petroleum diesel"]},
{"id":"l3-chemistry-natural-antibiotics","title":"Evidence-Based Natural Antimicrobials","category":"L3_materials_elements","subtopic":"basic_chemistry","tags":["antibiotics","antimicrobial","honey","garlic","colloidal-silver"],"region_relevance":["global"],"confidence":"medium","sources":["openstax-microbiology","who-basic-emergency-care-2018"],"related_entries":["l5-health-herbal-medicine-reference","l1-medical-infection-prevention"],"summary":"Natural compounds with documented antimicrobial activity. NOT substitutes for antibiotics when available, but useful when pharmaceutical antibiotics are unavailable.","warnings":["These are NOT equivalent to pharmaceutical antibiotics","Serious infections (sepsis, meningitis, pneumonia) require evacuation even when using natural antimicrobials","Colloidal silver overuse causes argyria (permanent blue-gray skin discoloration)","None of these are effective against all bacteria"],"steps":["HONEY (topical only): manuka honey (MGO 400+) or raw local honey applied to wounds. Change dressing daily. Effective against staph, strep, E.coli.","RAW GARLIC: crush 2-3 cloves, let sit 10 min (activates allicin), consume raw. Repeat 3× daily. Broad-spectrum but destroyed by cooking.","OREGANO OIL: 2-3 drops under tongue 2× daily OR dilute in carrier oil for topical. Contains carvacrol (antimicrobial compound).","COLLOIDAL SILVER (controversial): 10-20 ppm solution, 1 tsp 3× daily. ONLY short-term use (<2 weeks). Overuse causes permanent discoloration.","TEA TREE OIL: topical only (toxic if ingested). 5-10% dilution for wound treatment.","These are adjuncts — always combine with proper wound care, drainage, and clean dressing changes"]},
{"id":"l3-chemistry-glass-basics","title":"Basic Glass Making from Sand","category":"L3_materials_elements","subtopic":"basic_chemistry","tags":["glass","silica","sand","flux","furnace"],"region_relevance":["global"],"confidence":"low","sources":["openstax-chemistry-2e","usgs-mineral-education"],"related_entries":["l3-chemistry-cement-basics","l3-chemistry-lime-production","l4-tool-kiln-principles"],"summary":"Glass is melted silica (sand) + flux (soda ash or potash) + stabilizer (lime). Requires 1400-1600°C sustained temperature. Primitive glass (bottle green, full of bubbles) is achievable with a forced-air furnace and local materials.","warnings":["Glass melting requires extreme temperatures — severe burn risk","Silica dust (from grinding sand) causes silicosis — work wet or wear mask","Molten glass looks identical to solid glass — assume everything near the furnace is dangerously hot","Early attempts produce brittle, bubbly, colored glass — functional but not optical quality"],"steps":["MATERIALS: clean silica sand (white beach sand or crushed quartz), soda ash or potash (from wood ash — see lye entry), and lime (from limestone). Ratio: 70% sand, 15% flux, 15% lime by weight.","Build a high-temperature furnace: clay-lined pit with forced air (bellows or blower). Charcoal fuel. Target temperature: 1400°C+. A pottery kiln capable of stoneware temperatures can work.","Mix ingredients thoroughly when DRY. Place in a crucible (clay pot rated for high heat).","Heat gradually over 2-4 hours to avoid thermal shock cracking the crucible. Maintain peak temperature for 1-2 hours until mixture is completely molten and homogeneous.","Pour into molds or roll on a flat surface (marver). Work quickly — glass stiffens as it cools.","Anneal (slow cool) over 12-24 hours to prevent stress cracks. Rapid cooling shatters glass.","Expect green tint (from iron impurities in sand) and bubbles (dissolved gases). Refined glass requires purer ingredients and skilled technique.","USES: bottles, jars, windows (cast and ground flat), beads, tools for working other materials"]},
{"id":"l3-chemistry-ink-paper","title":"Ink and Paper Making","category":"L3_materials_elements","subtopic":"basic_chemistry","tags":["ink","paper","writing","oak-galls","pulp"],"region_relevance":["global","temperate"],"confidence":"high","sources":["openstax-chemistry-2e"],"related_entries":["l5-edu-library-preservation","l5-comm-writing-systems"],"summary":"Writing materials made from local plants and minerals. Oak-gall ink (iron gall ink) is permanent and water-resistant. Paper from plant fiber pulp takes 1-2 days including drying.","warnings":["Oak-gall ink is mildly corrosive to metal nibs — use quill or reed pens","Fresh ink stains skin and fabric — work carefully","Paper-making uses large amounts of water — do near a water source","Lye used in pulp processing is caustic"],"steps":["OAK-GALL INK: collect oak galls (round growths on oak trees caused by wasps). Crush 10-12 galls, soak in 1 cup water for 2-3 days. Strain. Add rusty iron nails and let sit 1 week — iron reacts with tannic acid forming black ink. Add gum arabic (tree sap) as binder. Stores indefinitely.","CHARCOAL INK: grind charcoal to fine powder. Mix with water and gum arabic or hide glue. Less permanent than iron-gall but immediate.","PAPER PULP: soak plant fiber (cotton rags, linen, hemp, kozo bark, papyrus) in lye solution (wood ash water) for 24 hours. This breaks down lignin. Rinse thoroughly.","Beat fiber: pound with a mallet or process in water until it becomes a slurry of individual fibers. This takes 1-2 hours of hard work.","FORMING SHEETS: dilute pulp in a large tub of water (1 part pulp:20 parts water). Dip a frame with fine screen/cloth into the tub, lift horizontally, capturing a thin layer of fibers. Let drain.","Press between cloths and boards to remove water. Hang or lay flat to dry completely (24 hours). The result is rough handmade paper suitable for writing.","ALTERNATIVE - PAPYRUS: slice papyrus stems lengthwise into thin strips. Lay parallel, slightly overlapping. Lay a second layer perpendicular on top. Pound with mallet and press under weight for 24 hours. Dries into a writing surface."]},
{"id":"l3-minerals-iron-ore-indicators","title":"Field Indicators for Iron Deposits","category":"L3_materials_elements","subtopic":"rock_mineral_id","tags":["iron-ore","magnetite","hematite","prospecting","geology"],"region_relevance":["global"],"confidence":"medium","sources":["usgs-mineral-education","usgs-mrds"],"related_entries":["l3-minerals-ore-recognition","l5-metallurgy-iron-smelting"],"summary":"Recognizing iron deposits in the field. Magnetite and hematite are the primary ores. Limonite and bog iron are easier to smelt but lower grade. Surface indicators help locate workable deposits for primitive iron production.","warnings":["Iron ore alone is useless — you also need charcoal, flux (limestone), and a blast furnace capable of 1200°C+","Most visible iron ore is low grade — bloomery yields 10-30% metallic iron from ore by weight","Deep mining is extremely dangerous — only surface and shallow deposits are practical in survival","Modern steel is alloyed — primitive bloomery iron is soft and needs repeated heating and hammering to improve"],"steps":["MAGNETITE (Fe3O4): black metallic mineral, strongly magnetic (attracts compass, can be picked up with a magnet). Often found in beach/stream sands as black sand concentrations. Highest grade iron ore (72% iron content).","HEMATITE (Fe2O3): red to gray mineral, leaves a red-brown streak on unglazed porcelain or stone. Found in sedimentary layers and as 'kidney ore' (rounded nodules). 70% iron content.","LIMONITE: yellow-brown rusty deposits. Found near surface as bog iron (in wetlands, streams) or as a weathering product of other ores. Lower grade (50-60%) but easier to smelt due to lower melting point.","BOG IRON: orange-brown nodules or crusts in swamps, stream beds, and spring areas. Forms where groundwater deposits dissolved iron. Vikings smelted bog iron extensively. Can be harvested sustainably (reforms over years).","SURFACE INDICATORS: red soil (laterite), rust-stained rocks near springs, magnetic anomalies, heavy black sand concentrations in streams.","TESTING: streak test (hematite = red-brown, magnetite = black), magnet test, density (iron ores are heavy — sink in water, much heavier than most rocks).","Economically workable deposits need: surface access, nearby fuel source (wood for charcoal), limestone for flux, and water. Primitive iron production is extremely labor and fuel-intensive."]},
]
for e in L3: w(e, "L3_materials_elements")

print(f"\n=== Generated {len(L3)} L3 entries ===\n")
PYTHON

python tools/validate.py
python tools/build_index.py
echo "===  Wave complete ==="
